package cn.jbolt._admin.customtablerender.common.model;

import cn.jbolt._admin.customtablerender.common.model.base.BaseCustomBusiness;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;
import cn.jbolt.core.annotation.JBoltAutoCache;

/**
 * 系统业务定义
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@JBoltAutoCache
@TableBind(dataSource = "main" , table = "jbc_custom_business" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class CustomBusiness extends BaseCustomBusiness<CustomBusiness> {
}

