#项目配置主加载文件 用于确定部署方式和环境 根据环境配置去加载单独的配置文件
#系统名称
system_name =矽翔质管部管理系统
#系统版权所有人
system_copyright_company=©Hanzj
#系统版权所有人链接URL
system_copyright_link=https://www.siargo.com.cn/
#project deploy environment dev or pro
pdev=dev
#demo mode
demo_mode = false