package cn.jbolt._admin.customtablerender.common.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 系统业务定义
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCustomBusiness<M extends BaseCustomBusiness<M>> extends JBoltBaseModel<M>{
    /**主键ID*/
    public static final String ID = "id";
    /**业务名称*/
    public static final String NAME = "name";
    /**备注信息*/
    public static final String REMARK = "remark";
    /**创建时间*/
    public static final String CREATE_TIME = "create_time";
    /**更新时间*/
    public static final String UPDATE_TIME = "update_time";
    /**创建人*/
    public static final String CREATE_USER_ID = "create_user_id";
    /**更新人*/
    public static final String UPDATE_USER_ID = "update_user_id";
    /**是否启用*/
    public static final String ENABLE = "enable";
	/**
	 * 主键ID
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 业务名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 业务名称
	 */
	@JBoltField(name="name" ,columnName="name",type="String", remark="业务名称", required=true, maxLength=60, fixed=0, order=2)
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 备注信息
	 */
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	/**
	 * 备注信息
	 */
	@JBoltField(name="remark" ,columnName="remark",type="String", remark="备注信息", required=false, maxLength=255, fixed=0, order=3)
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	@JBoltField(name="createTime" ,columnName="create_time",type="Date", remark="创建时间", required=true, maxLength=19, fixed=0, order=4)
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	@JBoltField(name="updateTime" ,columnName="update_time",type="Date", remark="更新时间", required=false, maxLength=19, fixed=0, order=5)
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}

	/**
	 * 创建人
	 */
	public M setCreateUserId(java.lang.Long createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	/**
	 * 创建人
	 */
	@JBoltField(name="createUserId" ,columnName="create_user_id",type="Long", remark="创建人", required=true, maxLength=19, fixed=0, order=6)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getCreateUserId() {
		return getLong("create_user_id");
	}

	/**
	 * 更新人
	 */
	public M setUpdateUserId(java.lang.Long updateUserId) {
		set("update_user_id", updateUserId);
		return (M)this;
	}
	
	/**
	 * 更新人
	 */
	@JBoltField(name="updateUserId" ,columnName="update_user_id",type="Long", remark="更新人", required=false, maxLength=19, fixed=0, order=7)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getUpdateUserId() {
		return getLong("update_user_id");
	}

	/**
	 * 是否启用
	 */
	public M setEnable(java.lang.Boolean enable) {
		set("enable", enable);
		return (M)this;
	}
	
	/**
	 * 是否启用
	 */
	@JBoltField(name="enable" ,columnName="enable",type="Boolean", remark="是否启用", required=true, maxLength=1, fixed=0, order=8)
	public java.lang.Boolean getEnable() {
		return getBoolean("enable");
	}

}

