package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseApiCallLog;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔质管部：API调用日志表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_api_call_log" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class ApiCallLog extends BaseApiCallLog<ApiCallLog> {
}

