package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseCustomer;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;
import cn.jbolt.core.cache.JBoltDictionaryCache;

/**
 * 客户名称(Customer Name)
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_customer" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Customer extends BaseCustomer<Customer> {
	
}

