package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseDictionary;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * siargo数据字典
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_dictionary" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Dictionary extends BaseDictionary<Dictionary> {
}

