package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseDictionarytype;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * siargo数据字典类型
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_dictionarytype" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Dictionarytype extends BaseDictionarytype<Dictionarytype> {
}

