package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseDmsCategory;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔文件类别表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_dms_category" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class DmsCategory extends BaseDmsCategory<DmsCategory> {
}

