package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseDmsFile;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔文件管理主表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_dms_file" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class DmsFile extends BaseDmsFile<DmsFile> {
}

