package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseDmsFileKeyword;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔文件关键字表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_dms_file_keyword" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class DmsFileKeyword extends BaseDmsFileKeyword<DmsFileKeyword> {
}

