package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseEquipmentRepair;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔质管部：设备维修记录表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_equipment_repair" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class EquipmentRepair extends BaseEquipmentRepair<EquipmentRepair> {
}

