package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseEquipment;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔质管部：监测设备台账主表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_equipment" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Equipment extends BaseEquipment<Equipment> {
}

