package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseEquipmentComparison;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔质管部：设备对比记录表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_equipment_comparison" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class EquipmentComparison extends BaseEquipmentComparison<EquipmentComparison> {
}

