package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseEquipmentCertificate;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔质管部：设备证书图片表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_equipment_certificate" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class EquipmentCertificate extends BaseEquipmentCertificate<EquipmentCertificate> {
}

