package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseEquipmentInspectionBatch;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔质管部：检校批次表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_equipment_inspection_batch" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class EquipmentInspectionBatch extends BaseEquipmentInspectionBatch<EquipmentInspectionBatch> {
}

