package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseImage;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 到货单图片存储表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_image" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Image extends BaseImage<Image> {
}

