package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BasePdfFolder;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔质管部：PDF版号路径配置表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_pdf_folder" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class PdfFolder extends BasePdfFolder<PdfFolder> {
}

