package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BasePdfTemplateProd;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔质管部：报告单模板-产品型号对照表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_pdf_template_prod" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class PdfTemplateProd extends BasePdfTemplateProd<PdfTemplateProd> {
}

