package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BasePdfTemplate;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔质管部：PDF模板型号匹配规则表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_pdf_template" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class PdfTemplate extends BasePdfTemplate<PdfTemplate> {
}

