package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseProductRejectLog;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔质管部：产品驳回历史
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_product_reject_log" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class ProductRejectLog extends BaseProductRejectLog<ProductRejectLog> {
}

