package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseProdModel;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔质管部：产品解析主表-保存通用型号系列及通用类型描述
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_prod_model" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class ProdModel extends BaseProdModel<ProdModel> {
}

