package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseProdModelParam;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔质管部：产品解析参数附表-主表与参数种类值的多对多关联表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_prod_model_param" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class ProdModelParam extends BaseProdModelParam<ProdModelParam> {
}

