package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseProdParamType;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔质管部：产品参数种类表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_prod_param_type" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class ProdParamType extends BaseProdParamType<ProdParamType> {
}

