package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseProdParamValue;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔质管部：产品参数种类值表
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_prod_param_value" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class ProdParamValue extends BaseProdParamValue<ProdParamValue> {
}

