package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseProdModelDimension;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 产品系列机械尺寸图（一系列多图）
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_prod_model_dimension" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class ProdModelDimension extends BaseProdModelDimension<ProdModelDimension> {
}

