package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseProdTechnicalParam;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 产品系列技术参数
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_prod_technical_param" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class ProdTechnicalParam extends BaseProdTechnicalParam<ProdTechnicalParam> {
}

