package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseQareport;

import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔质管部：检验报告单(Quality Report)
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_qareport" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Qareport extends BaseQareport<Qareport> {
	 
}

