package cn.jbolt.siargo.model;

import cn.jbolt.siargo.model.base.BaseSupplier;
import cn.jbolt.core.annotation.TableBind;
import cn.jbolt.core.base.JBoltIDGenMode;

/**
 * 矽翔供应商管理
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
@TableBind(dataSource = "main" , table = "siargo_supplier" , primaryKey = "id" , idGenMode = JBoltIDGenMode.SNOWFLAKE)
public class Supplier extends BaseSupplier<Supplier> {
}

