package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔质管部：产品解析主表-保存通用型号系列及通用类型描述
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProdModel<M extends BaseProdModel<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /**主键(雪花ID)*/
    public static final String ID = "id";
    /**通用型号/系列，如FS4308；同时作为解析匹配键*/
    public static final String MODEL_SERIES = "model_series";
    /**通用类型描述：系列-种类id-种类id-...（各段位按种类表sort_rank顺序引用siargo_prod_param_type.id）*/
    public static final String MODEL_DESC = "model_desc";
    /**产品类型(字典siargo_prod_type sn：1气体质量流量传感器/2气体质量流量计/3气体质量流量控制器/4微压差传感器/5液体流量计/6配件)*/
    public static final String PROD_TYPE = "prod_type";
    /**1启用/0停用*/
    public static final String IS_ACTIVE = "is_active";
    /**备注*/
    public static final String REMARK = "remark";
    /**产品简介*/
    public static final String PRODUCT_INTRO = "product_intro";
    /**产品特点，每行一项*/
    public static final String PRODUCT_FEATURES = "product_features";
	/**
	 * 主键(雪花ID)
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键(雪花ID)
	 */
	@JBoltField(name="id" ,columnName="id",type="Long", remark="主键(雪花ID)", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 通用型号/系列，如FS4308；同时作为解析匹配键
	 */
	public M setModelSeries(java.lang.String modelSeries) {
		set("model_series", modelSeries);
		return (M)this;
	}
	
	/**
	 * 通用型号/系列，如FS4308；同时作为解析匹配键
	 */
	@JBoltField(name="modelSeries" ,columnName="model_series",type="String", remark="通用型号/系列，如FS4308；同时作为解析匹配键", required=true, maxLength=50, fixed=0, order=2)
	public java.lang.String getModelSeries() {
		return getStr("model_series");
	}

	/**
	 * 通用类型描述：系列-种类id-种类id-...（各段位按种类表sort_rank顺序引用siargo_prod_param_type.id）
	 */
	public M setModelDesc(java.lang.String modelDesc) {
		set("model_desc", modelDesc);
		return (M)this;
	}
	
	/**
	 * 通用类型描述：系列-种类id-种类id-...（各段位按种类表sort_rank顺序引用siargo_prod_param_type.id）
	 */
	@JBoltField(name="modelDesc" ,columnName="model_desc",type="String", remark="通用类型描述：系列-种类id-种类id-...（各段位按种类表sort_rank顺序引用siargo_prod_param_type.id）", required=true, maxLength=500, fixed=0, order=3)
	public java.lang.String getModelDesc() {
		return getStr("model_desc");
	}

	/**
	 * 产品类型(字典siargo_prod_type sn：1气体质量流量传感器/2气体质量流量计/3气体质量流量控制器/4微压差传感器/5液体流量计/6配件)
	 */
	public M setProdType(java.lang.Integer prodType) {
		set("prod_type", prodType);
		return (M)this;
	}
	
	/**
	 * 产品类型(字典siargo_prod_type sn：1气体质量流量传感器/2气体质量流量计/3气体质量流量控制器/4微压差传感器/5液体流量计/6配件)
	 */
	@JBoltField(name="prodType" ,columnName="prod_type",type="Integer", remark="产品类型(字典siargo_prod_type sn：1气体质量流量传感器/2气体质量流量计/3气体质量流量控制器/4微压差传感器/5液体流量计/6配件)", required=true, maxLength=3, fixed=0, order=4)
	public java.lang.Integer getProdType() {
		return getInt("prod_type");
	}

	/**
	 * 1启用/0停用
	 */
	public M setIsActive(java.lang.Integer isActive) {
		set("is_active", isActive);
		return (M)this;
	}
	
	/**
	 * 1启用/0停用
	 */
	@JBoltField(name="isActive" ,columnName="is_active",type="Integer", remark="1启用/0停用", required=true, maxLength=3, fixed=0, order=5)
	public java.lang.Integer getIsActive() {
		return getInt("is_active");
	}

	/**
	 * 备注
	 */
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	/**
	 * 备注
	 */
	@JBoltField(name="remark" ,columnName="remark",type="String", remark="备注", required=false, maxLength=200, fixed=0, order=6)
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 产品简介
	 */
	public M setProductIntro(java.lang.String productIntro) {
		set("product_intro", productIntro);
		return (M)this;
	}
	
	/**
	 * 产品简介
	 */
	@JBoltField(name="productIntro" ,columnName="product_intro",type="String", remark="产品简介", required=false, maxLength=65535, fixed=0, order=7)
	public java.lang.String getProductIntro() {
		return getStr("product_intro");
	}

	/**
	 * 产品特点，每行一项
	 */
	public M setProductFeatures(java.lang.String productFeatures) {
		set("product_features", productFeatures);
		return (M)this;
	}
	
	/**
	 * 产品特点，每行一项
	 */
	@JBoltField(name="productFeatures" ,columnName="product_features",type="String", remark="产品特点，每行一项", required=false, maxLength=65535, fixed=0, order=8)
	public java.lang.String getProductFeatures() {
		return getStr("product_features");
	}


}

