package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔文件管理主表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDmsFile<M extends BaseDmsFile<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /**主键ID*/
    public static final String ID = "id";
    /**文件类别ID*/
    public static final String CATEGORY_ID = "category_id";
    /**文件名*/
    public static final String FILE_NAME = "file_name";
    /**文件存储路径*/
    public static final String FILE_PATH = "file_path";
    /**文件扩展名*/
    public static final String FILE_EXT = "file_ext";
    /**文件描述*/
    public static final String DESCRIPTION = "description";
    /**文件修改日期（业务日期）*/
    public static final String MODIFY_DATE = "modify_date";
    /**是否生效：1-生效，0-未生效*/
    public static final String IS_ACTIVE = "is_active";
    /**生效日期（用户手动输入）*/
    public static final String ACTIVE_DATE = "active_date";
    /**上传时间*/
    public static final String UPLOAD_TIME = "upload_time";
    /**上传者ID*/
    public static final String UPLOADER_ID = "uploader_id";
    /**状态：1-正常，0-删除*/
    public static final String STATUS = "status";
    /**删除时间*/
    public static final String DELETED_TIME = "deleted_time";
	/**
	 * 主键ID
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 文件类别ID
	 */
	public M setCategoryId(java.lang.Long categoryId) {
		set("category_id", categoryId);
		return (M)this;
	}
	
	/**
	 * 文件类别ID
	 */
	@JBoltField(name="categoryId" ,columnName="category_id",type="Long", remark="文件类别ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getCategoryId() {
		return getLong("category_id");
	}

	/**
	 * 文件名
	 */
	public M setFileName(java.lang.String fileName) {
		set("file_name", fileName);
		return (M)this;
	}
	
	/**
	 * 文件名
	 */
	@JBoltField(name="fileName" ,columnName="file_name",type="String", remark="文件名", required=true, maxLength=500, fixed=0, order=3)
	public java.lang.String getFileName() {
		return getStr("file_name");
	}

	/**
	 * 文件存储路径
	 */
	public M setFilePath(java.lang.String filePath) {
		set("file_path", filePath);
		return (M)this;
	}
	
	/**
	 * 文件存储路径
	 */
	@JBoltField(name="filePath" ,columnName="file_path",type="String", remark="文件存储路径", required=true, maxLength=500, fixed=0, order=4)
	public java.lang.String getFilePath() {
		return getStr("file_path");
	}

	/**
	 * 文件扩展名
	 */
	public M setFileExt(java.lang.String fileExt) {
		set("file_ext", fileExt);
		return (M)this;
	}
	
	/**
	 * 文件扩展名
	 */
	@JBoltField(name="fileExt" ,columnName="file_ext",type="String", remark="文件扩展名", required=false, maxLength=20, fixed=0, order=5)
	public java.lang.String getFileExt() {
		return getStr("file_ext");
	}

	/**
	 * 文件描述
	 */
	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	/**
	 * 文件描述
	 */
	@JBoltField(name="description" ,columnName="description",type="String", remark="文件描述", required=false, maxLength=1000, fixed=0, order=6)
	public java.lang.String getDescription() {
		return getStr("description");
	}

	/**
	 * 文件修改日期（业务日期）
	 */
	public M setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
		return (M)this;
	}
	
	/**
	 * 文件修改日期（业务日期）
	 */
	@JBoltField(name="modifyDate" ,columnName="modify_date",type="Date", remark="文件修改日期（业务日期）", required=false, maxLength=10, fixed=0, order=7)
	public java.util.Date getModifyDate() {
		return getDate("modify_date");
	}

	/**
	 * 是否生效：1-生效，0-未生效
	 */
	public M setIsActive(java.lang.Integer isActive) {
		set("is_active", isActive);
		return (M)this;
	}
	
	/**
	 * 是否生效：1-生效，0-未生效
	 */
	@JBoltField(name="isActive" ,columnName="is_active",type="Integer", remark="是否生效：1-生效，0-未生效", required=true, maxLength=3, fixed=0, order=8)
	public java.lang.Integer getIsActive() {
		return getInt("is_active");
	}

	/**
	 * 生效日期（用户手动输入）
	 */
	public M setActiveDate(java.util.Date activeDate) {
		set("active_date", activeDate);
		return (M)this;
	}
	
	/**
	 * 生效日期（用户手动输入）
	 */
	@JBoltField(name="activeDate" ,columnName="active_date",type="Date", remark="生效日期（用户手动输入）", required=false, maxLength=10, fixed=0, order=9)
	public java.util.Date getActiveDate() {
		return getDate("active_date");
	}

	/**
	 * 上传时间
	 */
	public M setUploadTime(java.util.Date uploadTime) {
		set("upload_time", uploadTime);
		return (M)this;
	}
	
	/**
	 * 上传时间
	 */
	@JBoltField(name="uploadTime" ,columnName="upload_time",type="Date", remark="上传时间", required=true, maxLength=19, fixed=0, order=10)
	public java.util.Date getUploadTime() {
		return getDate("upload_time");
	}

	/**
	 * 上传者ID
	 */
	public M setUploaderId(java.lang.Long uploaderId) {
		set("uploader_id", uploaderId);
		return (M)this;
	}
	
	/**
	 * 上传者ID
	 */
	@JBoltField(name="uploaderId" ,columnName="uploader_id",type="Long", remark="上传者ID", required=false, maxLength=19, fixed=0, order=11)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getUploaderId() {
		return getLong("uploader_id");
	}

	/**
	 * 状态：1-正常，0-删除
	 */
	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	/**
	 * 状态：1-正常，0-删除
	 */
	@JBoltField(name="status" ,columnName="status",type="Integer", remark="状态：1-正常，0-删除", required=true, maxLength=3, fixed=0, order=12)
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 删除时间
	 */
	public M setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
		return (M)this;
	}
	
	/**
	 * 删除时间
	 */
	@JBoltField(name="deletedTime" ,columnName="deleted_time",type="Date", remark="删除时间", required=false, maxLength=19, fixed=0, order=13)
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}

}

