package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔质管部：产品参数种类表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProdParamType<M extends BaseProdParamType<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /**主键(雪花ID)*/
    public static final String ID = "id";
    /**种类名称：最大流量/机械接口/输出方式/气体介质*/
    public static final String TYPE_NAME = "type_name";
    /**种类顺序(前端显示顺序)*/
    public static final String SORT_RANK = "sort_rank";
    /**1启用/0停用*/
    public static final String IS_ACTIVE = "is_active";
	/**
	 * 主键(雪花ID)
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键(雪花ID)
	 */
	@JBoltField(name="id" ,columnName="id",type="Long", remark="主键(雪花ID)", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 种类名称：最大流量/机械接口/输出方式/气体介质
	 */
	public M setTypeName(java.lang.String typeName) {
		set("type_name", typeName);
		return (M)this;
	}
	
	/**
	 * 种类名称：最大流量/机械接口/输出方式/气体介质
	 */
	@JBoltField(name="typeName" ,columnName="type_name",type="String", remark="种类名称：最大流量/机械接口/输出方式/气体介质", required=true, maxLength=20, fixed=0, order=2)
	public java.lang.String getTypeName() {
		return getStr("type_name");
	}

	/**
	 * 种类顺序(决定主表model_desc段位拼接顺序)
	 */
	public M setSortRank(java.lang.Integer sortRank) {
		set("sort_rank", sortRank);
		return (M)this;
	}
	
	/**
	 * 种类顺序(决定主表model_desc段位拼接顺序)
	 */
	@JBoltField(name="sortRank" ,columnName="sort_rank",type="Integer", remark="种类顺序(决定主表model_desc段位拼接顺序)", required=true, maxLength=10, fixed=0, order=3)
	public java.lang.Integer getSortRank() {
		return getInt("sort_rank");
	}

	/**
	 * 1启用/0停用
	 */
	public M setIsActive(java.lang.Integer isActive) {
		set("is_active", isActive);
		return (M)this;
	}
	
	/**
	 * 1启用/0停用
	 */
	@JBoltField(name="isActive" ,columnName="is_active",type="Integer", remark="1启用/0停用", required=true, maxLength=3, fixed=0, order=4)
	public java.lang.Integer getIsActive() {
		return getInt("is_active");
	}

}

