package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔供应商管理
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSupplier<M extends BaseSupplier<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /***/
    public static final String ID = "id";
    /**名称*/
    public static final String NAME = "name";
    /**排序*/
    public static final String SORT_RANK = "sort_rank";
    /**类型：1-机加，2-电子来料*/
    public static final String TYPE = "type";
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	@JBoltField(name="id" ,columnName="id",type="Long", remark="ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 名称
	 */
	@JBoltField(name="name" ,columnName="name",type="String", remark="名称", required=false, maxLength=255, fixed=0, order=2)
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 排序
	 */
	public M setSortRank(java.lang.Integer sortRank) {
		set("sort_rank", sortRank);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	@JBoltField(name="sortRank" ,columnName="sort_rank",type="Integer", remark="排序", required=false, maxLength=10, fixed=0, order=3)
	public java.lang.Integer getSortRank() {
		return getInt("sort_rank");
	}

	/**
	 * 类型：1-机加，2-电子来料
	 */
	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 类型：1-机加，2-电子来料
	 */
	@JBoltField(name="type" ,columnName="type",type="Integer", remark="类型：1-机加，2-电子来料", required=false, maxLength=10, fixed=0, order=4)
	public java.lang.Integer getType() {
		return getInt("type");
	}

}

