package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * siargo数据字典
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDictionary<M extends BaseDictionary<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /***/
    public static final String ID = "id";
    /***/
    public static final String TYPE_ID = "type_id";
    /***/
    public static final String KEY = "key";
    /***/
    public static final String VALUE = "value";
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	@JBoltField(name="id" ,columnName="id",type="Long", remark="ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setTypeId(java.lang.Long typeId) {
		set("type_id", typeId);
		return (M)this;
	}
	
	@JBoltField(name="typeId" ,columnName="type_id",type="Long", remark="TYPEID", required=false, maxLength=19, fixed=0, order=2)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getTypeId() {
		return getLong("type_id");
	}

	public M setKey(java.lang.String key) {
		set("key", key);
		return (M)this;
	}
	
	@JBoltField(name="key" ,columnName="key",type="String", remark="KEY", required=false, maxLength=255, fixed=0, order=3)
	public java.lang.String getKey() {
		return getStr("key");
	}

	public M setValue(java.lang.String value) {
		set("value", value);
		return (M)this;
	}
	
	@JBoltField(name="value" ,columnName="value",type="String", remark="VALUE", required=false, maxLength=255, fixed=0, order=4)
	public java.lang.String getValue() {
		return getStr("value");
	}

}

