package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔质管部：设备维修记录表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEquipmentRepair<M extends BaseEquipmentRepair<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /**主键（雪花ID）*/
    public static final String ID = "id";
    /**设备ID*/
    public static final String EQUIPMENT_ID = "equipment_id";
    /**触发维修的对比记录ID（可空，表示主动维修）*/
    public static final String COMPARISON_ID = "comparison_id";
    /**维修类型：1-公司维修 2-寄出维修*/
    public static final String REPAIR_TYPE = "repair_type";
    /**维修/送修日期*/
    public static final String REPAIR_DATE = "repair_date";
    /**故障描述*/
    public static final String FAULT_DESCRIPTION = "fault_description";
    /**维修措施*/
    public static final String REPAIR_ACTION = "repair_action";
    /**维修结果：0-维修中 1-已完成 2-无法修复*/
    public static final String REPAIR_RESULT = "repair_result";
    /**维修完成日期*/
    public static final String COMPLETION_DATE = "completion_date";
    /**维修人/维修单位*/
    public static final String REPAIRER = "repairer";
	/**
	 * 主键（雪花ID）
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键（雪花ID）
	 */
	@JBoltField(name="id" ,columnName="id",type="Long", remark="主键（雪花ID）", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 设备ID
	 */
	public M setEquipmentId(java.lang.Long equipmentId) {
		set("equipment_id", equipmentId);
		return (M)this;
	}
	
	/**
	 * 设备ID
	 */
	@JBoltField(name="equipmentId" ,columnName="equipment_id",type="Long", remark="设备ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getEquipmentId() {
		return getLong("equipment_id");
	}

	/**
	 * 触发维修的对比记录ID（可空，表示主动维修）
	 */
	public M setComparisonId(java.lang.Long comparisonId) {
		set("comparison_id", comparisonId);
		return (M)this;
	}
	
	/**
	 * 触发维修的对比记录ID（可空，表示主动维修）
	 */
	@JBoltField(name="comparisonId" ,columnName="comparison_id",type="Long", remark="触发维修的对比记录ID（可空，表示主动维修）", required=false, maxLength=19, fixed=0, order=3)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getComparisonId() {
		return getLong("comparison_id");
	}

	/**
	 * 维修类型：1-公司维修 2-寄出维修
	 */
	public M setRepairType(java.lang.Integer repairType) {
		set("repair_type", repairType);
		return (M)this;
	}
	
	/**
	 * 维修类型：1-公司维修 2-寄出维修
	 */
	@JBoltField(name="repairType" ,columnName="repair_type",type="Integer", remark="维修类型：1-公司维修 2-寄出维修", required=true, maxLength=3, fixed=0, order=4)
	public java.lang.Integer getRepairType() {
		return getInt("repair_type");
	}

	/**
	 * 维修/送修日期
	 */
	public M setRepairDate(java.util.Date repairDate) {
		set("repair_date", repairDate);
		return (M)this;
	}
	
	/**
	 * 维修/送修日期
	 */
	@JBoltField(name="repairDate" ,columnName="repair_date",type="Date", remark="维修/送修日期", required=true, maxLength=10, fixed=0, order=5)
	public java.util.Date getRepairDate() {
		return getDate("repair_date");
	}

	/**
	 * 故障描述
	 */
	public M setFaultDescription(java.lang.String faultDescription) {
		set("fault_description", faultDescription);
		return (M)this;
	}
	
	/**
	 * 故障描述
	 */
	@JBoltField(name="faultDescription" ,columnName="fault_description",type="String", remark="故障描述", required=false, maxLength=500, fixed=0, order=6)
	public java.lang.String getFaultDescription() {
		return getStr("fault_description");
	}

	/**
	 * 维修措施
	 */
	public M setRepairAction(java.lang.String repairAction) {
		set("repair_action", repairAction);
		return (M)this;
	}
	
	/**
	 * 维修措施
	 */
	@JBoltField(name="repairAction" ,columnName="repair_action",type="String", remark="维修措施", required=false, maxLength=500, fixed=0, order=7)
	public java.lang.String getRepairAction() {
		return getStr("repair_action");
	}

	/**
	 * 维修结果：0-维修中 1-已完成 2-无法修复
	 */
	public M setRepairResult(java.lang.Integer repairResult) {
		set("repair_result", repairResult);
		return (M)this;
	}
	
	/**
	 * 维修结果：1-维修中 2-已完成 3-无法修复
	 */
	@JBoltField(name="repairResult" ,columnName="repair_result",type="Integer", remark="维修结果：1-维修中 2-已完成 3-无法修复", required=true, maxLength=3, fixed=0, order=8)
	public java.lang.Integer getRepairResult() {
		return getInt("repair_result");
	}

	/**
	 * 维修完成日期
	 */
	public M setCompletionDate(java.util.Date completionDate) {
		set("completion_date", completionDate);
		return (M)this;
	}
	
	/**
	 * 维修完成日期
	 */
	@JBoltField(name="completionDate" ,columnName="completion_date",type="Date", remark="维修完成日期", required=false, maxLength=10, fixed=0, order=9)
	public java.util.Date getCompletionDate() {
		return getDate("completion_date");
	}

	/**
	 * 维修人/维修单位
	 */
	public M setRepairer(java.lang.String repairer) {
		set("repairer", repairer);
		return (M)this;
	}
	
	/**
	 * 维修人/维修单位
	 */
	@JBoltField(name="repairer" ,columnName="repairer",type="String", remark="维修人/维修单位", required=false, maxLength=50, fixed=0, order=10)
	public java.lang.String getRepairer() {
		return getStr("repairer");
	}

}

