package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔质管部：PDF模板型号匹配规则表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePdfTemplate<M extends BasePdfTemplate<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /**雪花算法主键*/
    public static final String ID = "id";
    /**版号(关联siargo_pdf_folder.pdfver)*/
    public static final String PDFVER = "pdfver";
    /**产品类型(1=传感器,2=小流量,3=大流量)*/
    public static final String PROD_TYPE = "prod_type";
    /**型号关键词(逗号分隔,任一contains匹配;NULL=不限型号兜底)*/
    public static final String MODEL_KEYWORDS = "model_keywords";
    /**模板文件名(如: 传感器模板.pdf)*/
    public static final String TEMPLATE_FILE = "template_file";
    /**错误提示关键词(如: 传感器)*/
    public static final String ERROR_HINT = "error_hint";
    /**同版号+同prod_type内优先级(越小越优先)*/
    public static final String PRIORITY = "priority";
    /**1=启用 0=停用*/
    public static final String IS_ACTIVE = "is_active";
	/**
	 * 雪花算法主键
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 雪花算法主键
	 */
	@JBoltField(name="id" ,columnName="id",type="Long", remark="雪花算法主键", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 版号(关联siargo_pdf_folder.pdfver)
	 */
	public M setPdfver(java.lang.String pdfver) {
		set("pdfver", pdfver);
		return (M)this;
	}
	
	/**
	 * 版号(关联siargo_pdf_folder.pdfver)
	 */
	@JBoltField(name="pdfver" ,columnName="pdfver",type="String", remark="版号(关联siargo_pdf_folder.pdfver)", required=true, maxLength=10, fixed=0, order=2)
	public java.lang.String getPdfver() {
		return getStr("pdfver");
	}

	/**
	 * 产品类型(1=传感器,2=小流量,3=大流量)
	 */
	public M setProdType(java.lang.String prodType) {
		set("prod_type", prodType);
		return (M)this;
	}
	
	/**
	 * 产品类型(1=传感器,2=小流量,3=大流量)
	 */
	@JBoltField(name="prodType" ,columnName="prod_type",type="String", remark="产品类型(1=传感器,2=小流量,3=大流量)", required=true, maxLength=10, fixed=0, order=3)
	public java.lang.String getProdType() {
		return getStr("prod_type");
	}

	/**
	 * 型号关键词(逗号分隔,任一contains匹配;NULL=不限型号兜底)
	 */
	public M setModelKeywords(java.lang.String modelKeywords) {
		set("model_keywords", modelKeywords);
		return (M)this;
	}
	
	/**
	 * 型号关键词(逗号分隔,任一contains匹配;NULL=不限型号兜底)
	 */
	@JBoltField(name="modelKeywords" ,columnName="model_keywords",type="String", remark="型号关键词(逗号分隔,任一contains匹配;NULL=不限型号兜底)", required=false, maxLength=500, fixed=0, order=4)
	public java.lang.String getModelKeywords() {
		return getStr("model_keywords");
	}

	/**
	 * 模板文件名(如: 传感器模板.pdf)
	 */
	public M setTemplateFile(java.lang.String templateFile) {
		set("template_file", templateFile);
		return (M)this;
	}
	
	/**
	 * 模板文件名(如: 传感器模板.pdf)
	 */
	@JBoltField(name="templateFile" ,columnName="template_file",type="String", remark="模板文件名(如: 传感器模板.pdf)", required=true, maxLength=100, fixed=0, order=5)
	public java.lang.String getTemplateFile() {
		return getStr("template_file");
	}

	/**
	 * 错误提示关键词(如: 传感器)
	 */
	public M setErrorHint(java.lang.String errorHint) {
		set("error_hint", errorHint);
		return (M)this;
	}
	
	/**
	 * 错误提示关键词(如: 传感器)
	 */
	@JBoltField(name="errorHint" ,columnName="error_hint",type="String", remark="错误提示关键词(如: 传感器)", required=true, maxLength=50, fixed=0, order=6)
	public java.lang.String getErrorHint() {
		return getStr("error_hint");
	}

	/**
	 * 同版号+同prod_type内优先级(越小越优先)
	 */
	public M setPriority(java.lang.Integer priority) {
		set("priority", priority);
		return (M)this;
	}
	
	/**
	 * 同版号+同prod_type内优先级(越小越优先)
	 */
	@JBoltField(name="priority" ,columnName="priority",type="Integer", remark="同版号+同prod_type内优先级(越小越优先)", required=true, maxLength=10, fixed=0, order=7)
	public java.lang.Integer getPriority() {
		return getInt("priority");
	}

	/**
	 * 1=启用 0=停用
	 */
	public M setIsActive(java.lang.Integer isActive) {
		set("is_active", isActive);
		return (M)this;
	}
	
	/**
	 * 1=启用 0=停用
	 */
	@JBoltField(name="isActive" ,columnName="is_active",type="Integer", remark="1=启用 0=停用", required=true, maxLength=3, fixed=0, order=8)
	public java.lang.Integer getIsActive() {
		return getInt("is_active");
	}

}

