package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 到货单图片存储表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseImage<M extends BaseImage<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /**主键ID*/
    public static final String ID = "id";
    /**供应商ID*/
    public static final String SUPPLIER_ID = "supplier_id";
    /**原始文件名*/
    public static final String ORIGINAL_NAME = "original_name";
    /**存储文件名（到货单号）*/
    public static final String STORAGE_NAME = "storage_name";
    /**文件存储路径*/
    public static final String FILE_PATH = "file_path";
    /**文件MD5值（去重）*/
    public static final String MD5_HASH = "md5_hash";
    /**图片描述*/
    public static final String DESCRIPTION = "description";
    /**上传时间*/
    public static final String UPLOAD_TIME = "upload_time";
    /**上传者ID*/
    public static final String UPLOADER_ID = "uploader_id";
    /**状态：1-正常，0-删除*/
    public static final String STATUS = "status";
    /**删除时间*/
    public static final String DELETED_TIME = "deleted_time";
	/**
	 * 主键ID
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 供应商ID
	 */
	public M setSupplierId(java.lang.String supplierId) {
		set("supplier_id", supplierId);
		return (M)this;
	}
	
	/**
	 * 供应商ID
	 */
	@JBoltField(name="supplierId" ,columnName="supplier_id",type="String", remark="供应商ID", required=true, maxLength=255, fixed=0, order=2)
	public java.lang.String getSupplierId() {
		return getStr("supplier_id");
	}

	/**
	 * 原始文件名
	 */
	public M setOriginalName(java.lang.String originalName) {
		set("original_name", originalName);
		return (M)this;
	}
	
	/**
	 * 原始文件名
	 */
	@JBoltField(name="originalName" ,columnName="original_name",type="String", remark="原始文件名", required=true, maxLength=255, fixed=0, order=3)
	public java.lang.String getOriginalName() {
		return getStr("original_name");
	}

	/**
	 * 存储文件名（到货单号）
	 */
	public M setStorageName(java.lang.String storageName) {
		set("storage_name", storageName);
		return (M)this;
	}
	
	/**
	 * 存储文件名（到货单号）
	 */
	@JBoltField(name="storageName" ,columnName="storage_name",type="String", remark="存储文件名（到货单号）", required=true, maxLength=100, fixed=0, order=4)
	public java.lang.String getStorageName() {
		return getStr("storage_name");
	}

	/**
	 * 文件存储路径
	 */
	public M setFilePath(java.lang.String filePath) {
		set("file_path", filePath);
		return (M)this;
	}
	
	/**
	 * 文件存储路径
	 */
	@JBoltField(name="filePath" ,columnName="file_path",type="String", remark="文件存储路径", required=true, maxLength=500, fixed=0, order=5)
	public java.lang.String getFilePath() {
		return getStr("file_path");
	}

	/**
	 * 文件MD5值（去重）
	 */
	public M setMd5Hash(java.lang.String md5Hash) {
		set("md5_hash", md5Hash);
		return (M)this;
	}
	
	/**
	 * 文件MD5值（去重）
	 */
	@JBoltField(name="md5Hash" ,columnName="md5_hash",type="String", remark="文件MD5值（去重）", required=true, maxLength=32, fixed=0, order=6)
	public java.lang.String getMd5Hash() {
		return getStr("md5_hash");
	}

	/**
	 * 图片描述
	 */
	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	/**
	 * 图片描述
	 */
	@JBoltField(name="description" ,columnName="description",type="String", remark="图片描述", required=false, maxLength=500, fixed=0, order=7)
	public java.lang.String getDescription() {
		return getStr("description");
	}

	/**
	 * 上传时间
	 */
	public M setUploadTime(java.util.Date uploadTime) {
		set("upload_time", uploadTime);
		return (M)this;
	}
	
	/**
	 * 上传时间
	 */
	@JBoltField(name="uploadTime" ,columnName="upload_time",type="Date", remark="上传时间", required=true, maxLength=19, fixed=0, order=8)
	public java.util.Date getUploadTime() {
		return getDate("upload_time");
	}

	/**
	 * 上传者ID
	 */
	public M setUploaderId(java.lang.Long uploaderId) {
		set("uploader_id", uploaderId);
		return (M)this;
	}
	
	/**
	 * 上传者ID
	 */
	@JBoltField(name="uploaderId" ,columnName="uploader_id",type="Long", remark="上传者ID", required=false, maxLength=19, fixed=0, order=9)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getUploaderId() {
		return getLong("uploader_id");
	}

	/**
	 * 状态：1-正常，0-删除
	 */
	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	/**
	 * 状态：1-正常，0-删除
	 */
	@JBoltField(name="status" ,columnName="status",type="Integer", remark="状态：1-正常，0-删除", required=true, maxLength=3, fixed=0, order=10)
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 删除时间
	 */
	public M setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
		return (M)this;
	}
	
	/**
	 * 删除时间
	 */
	@JBoltField(name="deletedTime" ,columnName="deleted_time",type="Date", remark="删除时间", required=false, maxLength=19, fixed=0, order=11)
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}

}

