package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔质管部：设备证书图片表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEquipmentCertificate<M extends BaseEquipmentCertificate<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /***/
    public static final String ID = "id";
    /**关联记录ID（siargo_equipment_record.id）*/
    public static final String RECORD_ID = "record_id";
    /**设备ID（冗余，加速按设备查证书）*/
    public static final String EQUIPMENT_ID = "equipment_id";
    /**证书图片地址*/
    public static final String IMAGE_URL = "image_url";
    /**证书日期*/
    public static final String CERTIFICATE_DATE = "certificate_date";
    /**备注*/
    public static final String REMARK = "remark";
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	@JBoltField(name="id" ,columnName="id",type="Long", remark="ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 关联记录ID（siargo_equipment_record.id）
	 */
	public M setRecordId(java.lang.Long recordId) {
		set("record_id", recordId);
		return (M)this;
	}
	
	/**
	 * 关联记录ID（siargo_equipment_record.id）
	 */
	@JBoltField(name="recordId" ,columnName="record_id",type="Long", remark="关联记录ID（siargo_equipment_record.id）", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getRecordId() {
		return getLong("record_id");
	}

	/**
	 * 设备ID（冗余，加速按设备查证书）
	 */
	public M setEquipmentId(java.lang.Long equipmentId) {
		set("equipment_id", equipmentId);
		return (M)this;
	}
	
	/**
	 * 设备ID（冗余，加速按设备查证书）
	 */
	@JBoltField(name="equipmentId" ,columnName="equipment_id",type="Long", remark="设备ID（冗余，加速按设备查证书）", required=true, maxLength=19, fixed=0, order=3)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getEquipmentId() {
		return getLong("equipment_id");
	}

	/**
	 * 证书图片地址
	 */
	public M setImageUrl(java.lang.String imageUrl) {
		set("image_url", imageUrl);
		return (M)this;
	}
	
	/**
	 * 证书图片地址
	 */
	@JBoltField(name="imageUrl" ,columnName="image_url",type="String", remark="证书图片地址", required=true, maxLength=500, fixed=0, order=4)
	public java.lang.String getImageUrl() {
		return getStr("image_url");
	}

	/**
	 * 证书日期
	 */
	public M setCertificateDate(java.util.Date certificateDate) {
		set("certificate_date", certificateDate);
		return (M)this;
	}
	
	/**
	 * 证书日期
	 */
	@JBoltField(name="certificateDate" ,columnName="certificate_date",type="Date", remark="证书日期", required=false, maxLength=10, fixed=0, order=5)
	public java.util.Date getCertificateDate() {
		return getDate("certificate_date");
	}

	/**
	 * 备注
	 */
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	/**
	 * 备注
	 */
	@JBoltField(name="remark" ,columnName="remark",type="String", remark="备注", required=false, maxLength=255, fixed=0, order=6)
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}

