package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔质管部：产品解析参数附表-主表与参数种类值的多对多关联表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProdModelParam<M extends BaseProdModelParam<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /**主键(雪花ID)*/
    public static final String ID = "id";
    /**产品解析主表id(siargo_prod_model.id)*/
    public static final String MODEL_ID = "model_id";
    /**参数种类id(siargo_prod_param_type.id)*/
    public static final String PARAM_TYPE_ID = "param_type_id";
    /**参数种类值id(siargo_prod_param_value.id)*/
    public static final String PARAM_VALUE_ID = "param_value_id";
	/**
	 * 主键(雪花ID)
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键(雪花ID)
	 */
	@JBoltField(name="id" ,columnName="id",type="Long", remark="主键(雪花ID)", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 产品解析主表id(siargo_prod_model.id)
	 */
	public M setModelId(java.lang.Long modelId) {
		set("model_id", modelId);
		return (M)this;
	}
	
	/**
	 * 产品解析主表id(siargo_prod_model.id)
	 */
	@JBoltField(name="modelId" ,columnName="model_id",type="Long", remark="产品解析主表id(siargo_prod_model.id)", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getModelId() {
		return getLong("model_id");
	}

	/**
	 * 参数种类id(siargo_prod_param_type.id)
	 */
	public M setParamTypeId(java.lang.Long paramTypeId) {
		set("param_type_id", paramTypeId);
		return (M)this;
	}
	
	/**
	 * 参数种类id(siargo_prod_param_type.id)
	 */
	@JBoltField(name="paramTypeId" ,columnName="param_type_id",type="Long", remark="参数种类id(siargo_prod_param_type.id)", required=true, maxLength=19, fixed=0, order=3)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getParamTypeId() {
		return getLong("param_type_id");
	}

	/**
	 * 参数种类值id(siargo_prod_param_value.id)
	 */
	public M setParamValueId(java.lang.Long paramValueId) {
		set("param_value_id", paramValueId);
		return (M)this;
	}
	
	/**
	 * 参数种类值id(siargo_prod_param_value.id)
	 */
	@JBoltField(name="paramValueId" ,columnName="param_value_id",type="Long", remark="参数种类值id(siargo_prod_param_value.id)", required=true, maxLength=19, fixed=0, order=4)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getParamValueId() {
		return getLong("param_value_id");
	}

}

