package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔质管部：监测设备台账主表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEquipment<M extends BaseEquipment<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /***/
    public static final String ID = "id";
    /**设备分类，字典siargo_equipment_category的sn*/
    public static final String CATEGORY = "category";
    /**计量器具名称*/
    public static final String NAME = "name";
    /**规格型号*/
    public static final String MODEL = "model";
    /**器具编号，如SIAR/ET-CL-001*/
    public static final String EQUIPMENT_NO = "equipment_no";
    /**检定方式：外检/自校/自检*/
    public static final String INSPECTION_METHOD = "inspection_method";
    /**检校周期数值*/
    public static final String INSPECTION_CYCLE = "inspection_cycle";
    /**周期单位：月/年*/
    public static final String INSPECTION_CYCLE_UNIT = "inspection_cycle_unit";
    /**最近检校日期*/
    public static final String LAST_INSPECTION_DATE = "last_inspection_date";
    /**下次检校日期*/
    public static final String NEXT_INSPECTION_DATE = "next_inspection_date";
    /**使用地点*/
    public static final String LOCATION = "location";
    /**责任人*/
    public static final String RESPONSIBLE_PERSON = "responsible_person";
    /**生产厂家*/
    public static final String MANUFACTURER = "manufacturer";
    /**出厂编号*/
    public static final String FACTORY_NO = "factory_no";
    /**设备本身状态：1-合格 2-维修中 3-已封存 4-报废*/
    public static final String STATUS = "status";
    /**购入日期*/
    public static final String PURCHASE_DATE = "purchase_date";
    /**备注（保留原始备注文本）*/
    public static final String REMARK = "remark";
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	@JBoltField(name="id" ,columnName="id",type="Long", remark="ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 设备分类，字典siargo_equipment_category的sn
	 */
	public M setCategory(java.lang.String category) {
		set("category", category);
		return (M)this;
	}
	
	/**
	 * 设备分类，字典siargo_equipment_category的sn
	 */
	@JBoltField(name="category" ,columnName="category",type="String", remark="设备分类，字典siargo_equipment_category的sn", required=true, maxLength=30, fixed=0, order=2)
	public java.lang.String getCategory() {
		return getStr("category");
	}

	/**
	 * 计量器具名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 计量器具名称
	 */
	@JBoltField(name="name" ,columnName="name",type="String", remark="计量器具名称", required=true, maxLength=100, fixed=0, order=3)
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 规格型号
	 */
	public M setModel(java.lang.String model) {
		set("model", model);
		return (M)this;
	}
	
	/**
	 * 规格型号
	 */
	@JBoltField(name="model" ,columnName="model",type="String", remark="规格型号", required=false, maxLength=100, fixed=0, order=4)
	public java.lang.String getModel() {
		return getStr("model");
	}

	/**
	 * 器具编号，如SIAR/ET-CL-001
	 */
	public M setEquipmentNo(java.lang.String equipmentNo) {
		set("equipment_no", equipmentNo);
		return (M)this;
	}
	
	/**
	 * 器具编号，如SIAR/ET-CL-001
	 */
	@JBoltField(name="equipmentNo" ,columnName="equipment_no",type="String", remark="器具编号，如SIAR/ET-CL-001", required=true, maxLength=50, fixed=0, order=5)
	public java.lang.String getEquipmentNo() {
		return getStr("equipment_no");
	}

	/**
	 * 检定方式：外检/自校/自检
	 */
	public M setInspectionMethod(java.lang.String inspectionMethod) {
		set("inspection_method", inspectionMethod);
		return (M)this;
	}
	
	/**
	 * 检定方式：外检/自校/自检
	 */
	@JBoltField(name="inspectionMethod" ,columnName="inspection_method",type="String", remark="检定方式：外检/自校/自检", required=false, maxLength=20, fixed=0, order=6)
	public java.lang.String getInspectionMethod() {
		return getStr("inspection_method");
	}

	/**
	 * 检校周期数值
	 */
	public M setInspectionCycle(java.lang.Integer inspectionCycle) {
		set("inspection_cycle", inspectionCycle);
		return (M)this;
	}
	
	/**
	 * 检校周期数值
	 */
	@JBoltField(name="inspectionCycle" ,columnName="inspection_cycle",type="Integer", remark="检校周期数值", required=false, maxLength=10, fixed=0, order=7)
	public java.lang.Integer getInspectionCycle() {
		return getInt("inspection_cycle");
	}

	/**
	 * 周期单位：月/年
	 */
	public M setInspectionCycleUnit(java.lang.String inspectionCycleUnit) {
		set("inspection_cycle_unit", inspectionCycleUnit);
		return (M)this;
	}
	
	/**
	 * 周期单位：月/年
	 */
	@JBoltField(name="inspectionCycleUnit" ,columnName="inspection_cycle_unit",type="String", remark="周期单位：月/年", required=false, maxLength=10, fixed=0, order=8)
	public java.lang.String getInspectionCycleUnit() {
		return getStr("inspection_cycle_unit");
	}

	/**
	 * 最近检校日期
	 */
	public M setLastInspectionDate(java.util.Date lastInspectionDate) {
		set("last_inspection_date", lastInspectionDate);
		return (M)this;
	}
	
	/**
	 * 最近检校日期
	 */
	@JBoltField(name="lastInspectionDate" ,columnName="last_inspection_date",type="Date", remark="最近检校日期", required=false, maxLength=10, fixed=0, order=9)
	public java.util.Date getLastInspectionDate() {
		return getDate("last_inspection_date");
	}

	/**
	 * 下次检校日期
	 */
	public M setNextInspectionDate(java.util.Date nextInspectionDate) {
		set("next_inspection_date", nextInspectionDate);
		return (M)this;
	}
	
	/**
	 * 下次检校日期
	 */
	@JBoltField(name="nextInspectionDate" ,columnName="next_inspection_date",type="Date", remark="下次检校日期", required=false, maxLength=10, fixed=0, order=10)
	public java.util.Date getNextInspectionDate() {
		return getDate("next_inspection_date");
	}

	/**
	 * 使用地点
	 */
	public M setLocation(java.lang.String location) {
		set("location", location);
		return (M)this;
	}
	
	/**
	 * 使用地点
	 */
	@JBoltField(name="location" ,columnName="location",type="String", remark="使用地点", required=false, maxLength=50, fixed=0, order=11)
	public java.lang.String getLocation() {
		return getStr("location");
	}

	/**
	 * 责任人
	 */
	public M setResponsiblePerson(java.lang.String responsiblePerson) {
		set("responsible_person", responsiblePerson);
		return (M)this;
	}
	
	/**
	 * 责任人
	 */
	@JBoltField(name="responsiblePerson" ,columnName="responsible_person",type="String", remark="责任人", required=false, maxLength=30, fixed=0, order=12)
	public java.lang.String getResponsiblePerson() {
		return getStr("responsible_person");
	}

	/**
	 * 生产厂家
	 */
	public M setManufacturer(java.lang.String manufacturer) {
		set("manufacturer", manufacturer);
		return (M)this;
	}
	
	/**
	 * 生产厂家
	 */
	@JBoltField(name="manufacturer" ,columnName="manufacturer",type="String", remark="生产厂家", required=false, maxLength=100, fixed=0, order=13)
	public java.lang.String getManufacturer() {
		return getStr("manufacturer");
	}

	/**
	 * 出厂编号
	 */
	public M setFactoryNo(java.lang.String factoryNo) {
		set("factory_no", factoryNo);
		return (M)this;
	}
	
	/**
	 * 出厂编号
	 */
	@JBoltField(name="factoryNo" ,columnName="factory_no",type="String", remark="出厂编号", required=false, maxLength=100, fixed=0, order=14)
	public java.lang.String getFactoryNo() {
		return getStr("factory_no");
	}

	/**
	 * 设备本身状态：1-合格 2-维修中 3-已封存 4-报废
	 */
	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	/**
	 * 设备本身状态：1-合格 2-维修中 3-已封存 4-报废
	 */
	@JBoltField(name="status" ,columnName="status",type="Integer", remark="设备本身状态：1-合格 2-维修中 3-已封存 4-报废", required=true, maxLength=3, fixed=0, order=15)
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 购入日期
	 */
	public M setPurchaseDate(java.util.Date purchaseDate) {
		set("purchase_date", purchaseDate);
		return (M)this;
	}
	
	/**
	 * 购入日期
	 */
	@JBoltField(name="purchaseDate" ,columnName="purchase_date",type="Date", remark="购入日期", required=false, maxLength=10, fixed=0, order=16)
	public java.util.Date getPurchaseDate() {
		return getDate("purchase_date");
	}

	/**
	 * 备注（保留原始备注文本）
	 */
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	/**
	 * 备注（保留原始备注文本）
	 */
	@JBoltField(name="remark" ,columnName="remark",type="String", remark="备注（保留原始备注文本）", required=false, maxLength=65535, fixed=0, order=17)
	public java.lang.String getRemark() {
		return getStr("remark");
	}


}

