package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔质管部：检验报告单(Quality Report)
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQareport<M extends BaseQareport<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /**主键ID*/
    public static final String ID = "id";
    /**订单号*/
    public static final String ORDER_ID = "order_id";
    /**客户ID*/
    public static final String CUST_ID = "cust_id";
    /**表单编号(Form Number)*/
    public static final String FORMNUM = "formnum";
    /**产品类型：0大流量计，1小流量计，2传感器*/
    public static final String PROD_TYPE = "prod_type";
    /**报告单类型：0产成品，1返修品*/
    public static final String REP_TYPE = "rep_type";


    /**录入时间*/
    public static final String CREATE_TIME = "create_time";

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 订单号
	 */
	public M setOrderId(java.lang.Long orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	/**
	 * 订单号
	 */
	@JBoltField(name="orderId" ,columnName="order_id",type="Long", remark="订单号", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getOrderId() {
		return getLong("order_id");
	}

	/**
	 * 客户ID
	 */
	public M setCustId(java.lang.Long custId) {
		set("cust_id", custId);
		return (M)this;
	}
	
	/**
	 * 客户ID
	 */
	@JBoltField(name="custId" ,columnName="cust_id",type="Long", remark="客户ID", required=true, maxLength=19, fixed=0, order=3)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getCustId() {
		return getLong("cust_id");
	}

	/**
	 * 表单编号(Form Number)
	 */
	public M setFormnum(java.lang.Long formnum) {
		set("formnum", formnum);
		return (M)this;
	}
	
	/**
	 * 表单编号(Form Number)
	 */
	@JBoltField(name="formnum" ,columnName="formnum",type="Long", remark="表单编号(Form Number)", required=true, maxLength=10, fixed=0, order=4)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getFormnum() {
		return getLong("formnum");
	}

	/**
	 * 报告单类型：1产成品，2返修品
	 */
	public M setRepType(java.lang.Integer repType) {
		set("rep_type", repType);
		return (M)this;
	}
	
	/**
	 * 报告单类型：1产成品，2返修品
	 */
	@JBoltField(name="repType" ,columnName="rep_type",type="Integer", remark="报告单类型：0产成品，1返修品", required=true, maxLength=3, fixed=0, order=6)
	public java.lang.Integer getRepType() {
		return getInt("rep_type");
	}

	/**
	 * 录入时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 录入时间
	 */
	@JBoltField(name="createTime" ,columnName="create_time",type="Date", remark="录入时间", required=false, maxLength=19, fixed=0, order=7)
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	

}

