package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔质管部：PDF版号路径配置表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePdfFolder<M extends BasePdfFolder<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /**雪花算法主键*/
    public static final String ID = "id";
    /**版号(=jb_dictionary.sn, type_key=siargo_pdfver)*/
    public static final String PDFVER = "pdfver";
    /**关联jb_dictionary.id*/
    public static final String DICT_ID = "dict_id";
    /**模板存储路径(相对webapp,如: /_view/admin/siargo/pdf/templates/2)*/
    public static final String TEMPLATE_PATH = "template_path";
    /**日常PDF输出路径(相对webapp,如: /export/G/2)*/
    public static final String EXPORT_PATH = "export_path";
    /**版本描述*/
    public static final String DESCRIPTION = "description";
    /**1=启用 0=停用*/
    public static final String IS_ACTIVE = "is_active";
	/**
	 * 雪花算法主键
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 雪花算法主键
	 */
	@JBoltField(name="id" ,columnName="id",type="Long", remark="雪花算法主键", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 版号(=jb_dictionary.sn, type_key=siargo_pdfver)
	 */
	public M setPdfver(java.lang.String pdfver) {
		set("pdfver", pdfver);
		return (M)this;
	}
	
	/**
	 * 版号(=jb_dictionary.sn, type_key=siargo_pdfver)
	 */
	@JBoltField(name="pdfver" ,columnName="pdfver",type="String", remark="版号(=jb_dictionary.sn, type_key=siargo_pdfver)", required=true, maxLength=10, fixed=0, order=2)
	public java.lang.String getPdfver() {
		return getStr("pdfver");
	}

	/**
	 * 关联jb_dictionary.id
	 */
	public M setDictId(java.lang.Long dictId) {
		set("dict_id", dictId);
		return (M)this;
	}
	
	/**
	 * 关联jb_dictionary.id
	 */
	@JBoltField(name="dictId" ,columnName="dict_id",type="Long", remark="关联jb_dictionary.id", required=true, maxLength=19, fixed=0, order=3)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getDictId() {
		return getLong("dict_id");
	}

	/**
	 * 模板存储路径(相对webapp,如: /_view/admin/siargo/pdf/templates/2)
	 */
	public M setTemplatePath(java.lang.String templatePath) {
		set("template_path", templatePath);
		return (M)this;
	}
	
	/**
	 * 模板存储路径(相对webapp,如: /_view/admin/siargo/pdf/templates/2)
	 */
	@JBoltField(name="templatePath" ,columnName="template_path",type="String", remark="模板存储路径(相对webapp,如: /_view/admin/siargo/pdf/templates/2)", required=true, maxLength=255, fixed=0, order=4)
	public java.lang.String getTemplatePath() {
		return getStr("template_path");
	}

	/**
	 * 日常PDF输出路径(相对webapp,如: /export/G/2)
	 */
	public M setExportPath(java.lang.String exportPath) {
		set("export_path", exportPath);
		return (M)this;
	}
	
	/**
	 * 日常PDF输出路径(相对webapp,如: /export/G/2)
	 */
	@JBoltField(name="exportPath" ,columnName="export_path",type="String", remark="日常PDF输出路径(相对webapp,如: /export/G/2)", required=true, maxLength=255, fixed=0, order=5)
	public java.lang.String getExportPath() {
		return getStr("export_path");
	}

	/**
	 * 版本描述
	 */
	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	/**
	 * 版本描述
	 */
	@JBoltField(name="description" ,columnName="description",type="String", remark="版本描述", required=false, maxLength=200, fixed=0, order=6)
	public java.lang.String getDescription() {
		return getStr("description");
	}

	/**
	 * 1=启用 0=停用
	 */
	public M setIsActive(java.lang.Integer isActive) {
		set("is_active", isActive);
		return (M)this;
	}
	
	/**
	 * 1=启用 0=停用
	 */
	@JBoltField(name="isActive" ,columnName="is_active",type="Integer", remark="1=启用 0=停用", required=true, maxLength=3, fixed=0, order=7)
	public java.lang.Integer getIsActive() {
		return getInt("is_active");
	}

}

