package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔质管部：报告单模板-产品型号对照表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePdfTemplateProd<M extends BasePdfTemplateProd<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /***/
    public static final String ID = "id";
    /***/
    public static final String SIARGO_PDF_TEMPLATE_ID = "siargo_pdf_template_id";
    /***/
    public static final String SIARGO_PROD_MODEL_ID = "siargo_prod_model_id";
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	@JBoltField(name="id" ,columnName="id",type="Long", remark="ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setSiargoPdfTemplateId(java.lang.Long siargoPdfTemplateId) {
		set("siargo_pdf_template_id", siargoPdfTemplateId);
		return (M)this;
	}
	
	@JBoltField(name="siargoPdfTemplateId" ,columnName="siargo_pdf_template_id",type="Long", remark="SIARGOPDFTEMPLATEID", required=false, maxLength=19, fixed=0, order=2)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getSiargoPdfTemplateId() {
		return getLong("siargo_pdf_template_id");
	}

	public M setSiargoProdModelId(java.lang.Long siargoProdModelId) {
		set("siargo_prod_model_id", siargoProdModelId);
		return (M)this;
	}
	
	@JBoltField(name="siargoProdModelId" ,columnName="siargo_prod_model_id",type="Long", remark="SIARGOPRODMODELID", required=false, maxLength=19, fixed=0, order=3)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getSiargoProdModelId() {
		return getLong("siargo_prod_model_id");
	}

}

