package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔质管部：产品驳回历史
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProductRejectLog<M extends BaseProductRejectLog<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /**主键（雪花）*/
    public static final String ID = "id";
    /**产品ID，关联 siargo_product.id*/
    public static final String PRODUCT_ID = "product_id";
    /**驳回发生环节：2=外观检验 3=包装检验 4=批准*/
    public static final String REJECT_INSP = "reject_insp";
    /**驳回原因*/
    public static final String REJECT_DES = "reject_des";
    /**驳回人，关联 jb_user.id*/
    public static final String REJECT_UID = "reject_uid";
    /**驳回时间*/
    public static final String REJECT_TIME = "reject_time";
	/**
	 * 主键（雪花）
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键（雪花）
	 */
	@JBoltField(name="id" ,columnName="id",type="Long", remark="主键（雪花）", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 产品ID，关联 siargo_product.id
	 */
	public M setProductId(java.lang.Long productId) {
		set("product_id", productId);
		return (M)this;
	}
	
	/**
	 * 产品ID，关联 siargo_product.id
	 */
	@JBoltField(name="productId" ,columnName="product_id",type="Long", remark="产品ID，关联 siargo_product.id", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getProductId() {
		return getLong("product_id");
	}

	/**
	 * 驳回发生环节：2=外观检验 3=包装检验 4=批准
	 */
	public M setRejectInsp(java.lang.Integer rejectInsp) {
		set("reject_insp", rejectInsp);
		return (M)this;
	}
	
	/**
	 * 驳回发生环节：2=外观检验 3=包装检验 4=批准
	 */
	@JBoltField(name="rejectInsp" ,columnName="reject_insp",type="Integer", remark="驳回发生环节：2=外观检验 3=包装检验 4=批准", required=true, maxLength=3, fixed=0, order=3)
	public java.lang.Integer getRejectInsp() {
		return getInt("reject_insp");
	}

	/**
	 * 驳回原因
	 */
	public M setRejectDes(java.lang.String rejectDes) {
		set("reject_des", rejectDes);
		return (M)this;
	}
	
	/**
	 * 驳回原因
	 */
	@JBoltField(name="rejectDes" ,columnName="reject_des",type="String", remark="驳回原因", required=true, maxLength=500, fixed=0, order=4)
	public java.lang.String getRejectDes() {
		return getStr("reject_des");
	}

	/**
	 * 驳回人，关联 jb_user.id
	 */
	public M setRejectUid(java.lang.Long rejectUid) {
		set("reject_uid", rejectUid);
		return (M)this;
	}
	
	/**
	 * 驳回人，关联 jb_user.id
	 */
	@JBoltField(name="rejectUid" ,columnName="reject_uid",type="Long", remark="驳回人，关联 jb_user.id", required=true, maxLength=19, fixed=0, order=5)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getRejectUid() {
		return getLong("reject_uid");
	}

	/**
	 * 驳回时间
	 */
	public M setRejectTime(java.util.Date rejectTime) {
		set("reject_time", rejectTime);
		return (M)this;
	}
	
	/**
	 * 驳回时间
	 */
	@JBoltField(name="rejectTime" ,columnName="reject_time",type="Date", remark="驳回时间", required=true, maxLength=19, fixed=0, order=6)
	public java.util.Date getRejectTime() {
		return getDate("reject_time");
	}

}

