package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔质管部：设备维修校准记录表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEquipmentRecord<M extends BaseEquipmentRecord<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /***/
    public static final String ID = "id";
    /**设备ID*/
    public static final String EQUIPMENT_ID = "equipment_id";
    /**使用状态/记录类型，字典siargo_equipment_record_type的sn*/
    public static final String RECORD_TYPE = "record_type";
    /**事件日期*/
    public static final String RECORD_DATE = "record_date";
    /**事件描述*/
    public static final String DESCRIPTION = "description";
    /**处理人，关联jb_user.id*/
    public static final String USER_ID = "user_id";
    /**编制人，关联jb_user.id*/
    public static final String CREATOR_ID = "creator_id";
    /**审核人，关联jb_user.id*/
    public static final String AUDITOR_ID = "auditor_id";
    /**编制时间*/
    public static final String CREATOR_TIME = "creator_time";
    /**审核时间*/
    public static final String AUDITOR_TIME = "auditor_time";
    /**审核状态 0-未审核 1-待审核 2-已审核*/
    public static final String AUDIT_STATUS = "audit_status";
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	@JBoltField(name="id" ,columnName="id",type="Long", remark="ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 设备ID
	 */
	public M setEquipmentId(java.lang.Long equipmentId) {
		set("equipment_id", equipmentId);
		return (M)this;
	}
	
	/**
	 * 设备ID
	 */
	@JBoltField(name="equipmentId" ,columnName="equipment_id",type="Long", remark="设备ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getEquipmentId() {
		return getLong("equipment_id");
	}

	/**
	 * 使用状态/记录类型，字典siargo_equipment_record_type的sn
	 */
	public M setRecordType(java.lang.String recordType) {
		set("record_type", recordType);
		return (M)this;
	}
	
	/**
	 * 使用状态/记录类型，字典siargo_equipment_record_type的sn
	 */
	@JBoltField(name="recordType" ,columnName="record_type",type="String", remark="使用状态/记录类型，字典siargo_equipment_record_type的sn", required=true, maxLength=30, fixed=0, order=3)
	public java.lang.String getRecordType() {
		return getStr("record_type");
	}

	/**
	 * 事件日期
	 */
	public M setRecordDate(java.util.Date recordDate) {
		set("record_date", recordDate);
		return (M)this;
	}
	
	/**
	 * 事件日期
	 */
	@JBoltField(name="recordDate" ,columnName="record_date",type="Date", remark="事件日期", required=false, maxLength=10, fixed=0, order=4)
	public java.util.Date getRecordDate() {
		return getDate("record_date");
	}

	/**
	 * 事件描述
	 */
	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	/**
	 * 事件描述
	 */
	@JBoltField(name="description" ,columnName="description",type="String", remark="事件描述", required=true, maxLength=500, fixed=0, order=5)
	public java.lang.String getDescription() {
		return getStr("description");
	}

	/**
	 * 处理人，关联jb_user.id
	 */
	public M setUserId(java.lang.Long userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 处理人，关联jb_user.id
	 */
	@JBoltField(name="userId" ,columnName="user_id",type="Long", remark="处理人，关联jb_user.id", required=false, maxLength=19, fixed=0, order=7)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	/**
	 * 编制人，关联jb_user.id
	 */
	public M setCreatorId(java.lang.Long creatorId) {
		set("creator_id", creatorId);
		return (M)this;
	}
	
	/**
	 * 编制人，关联jb_user.id
	 */
	@JBoltField(name="creatorId" ,columnName="creator_id",type="Long", remark="编制人，关联jb_user.id", required=false, maxLength=19, fixed=0, order=8)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getCreatorId() {
		return getLong("creator_id");
	}

	/**
	 * 审核人，关联jb_user.id
	 */
	public M setAuditorId(java.lang.Long auditorId) {
		set("auditor_id", auditorId);
		return (M)this;
	}
	
	/**
	 * 审核人，关联jb_user.id
	 */
	@JBoltField(name="auditorId" ,columnName="auditor_id",type="Long", remark="审核人，关联jb_user.id", required=false, maxLength=19, fixed=0, order=9)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getAuditorId() {
		return getLong("auditor_id");
	}

	/**
	 * 编制时间
	 */
	public M setCreatorTime(java.util.Date creatorTime) {
		set("creator_time", creatorTime);
		return (M)this;
	}
	
	/**
	 * 编制时间
	 */
	@JBoltField(name="creatorTime" ,columnName="creator_time",type="Date", remark="编制时间", required=false, maxLength=19, fixed=0, order=10)
	public java.util.Date getCreatorTime() {
		return getDate("creator_time");
	}

	/**
	 * 审核时间
	 */
	public M setAuditorTime(java.util.Date auditorTime) {
		set("auditor_time", auditorTime);
		return (M)this;
	}
	
	/**
	 * 审核时间
	 */
	@JBoltField(name="auditorTime" ,columnName="auditor_time",type="Date", remark="审核时间", required=false, maxLength=19, fixed=0, order=11)
	public java.util.Date getAuditorTime() {
		return getDate("auditor_time");
	}

	/**
	 * 审核状态 0-未审核 1-待审核 2-已审核
	 */
	public M setAuditStatus(java.lang.Integer auditStatus) {
		set("audit_status", auditStatus);
		return (M)this;
	}
	
	/**
	 * 审核状态 0-未审核 1-待审核 2-已审核
	 */
	@JBoltField(name="auditStatus" ,columnName="audit_status",type="Integer", remark="审核状态 0-未审核 1-待审核 2-已审核", required=false, maxLength=3, fixed=0, order=12)
	public java.lang.Integer getAuditStatus() {
		return getInt("audit_status");
	}

}

