package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔文件类别表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDmsCategory<M extends BaseDmsCategory<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /**主键ID*/
    public static final String ID = "id";
    /**类别名称*/
    public static final String NAME = "name";
    /**排序号*/
    public static final String SORT_RANK = "sort_rank";
	/**
	 * 主键ID
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 类别名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 类别名称
	 */
	@JBoltField(name="name" ,columnName="name",type="String", remark="类别名称", required=true, maxLength=100, fixed=0, order=2)
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 排序号
	 */
	public M setSortRank(java.lang.Integer sortRank) {
		set("sort_rank", sortRank);
		return (M)this;
	}
	
	/**
	 * 排序号
	 */
	@JBoltField(name="sortRank" ,columnName="sort_rank",type="Integer", remark="排序号", required=true, maxLength=10, fixed=0, order=3)
	public java.lang.Integer getSortRank() {
		return getInt("sort_rank");
	}

}

