package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔质管部：产品系列技术参数
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProdTechnicalParam<M extends BaseProdTechnicalParam<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /**雪花ID*/
    public static final String ID = "id";
    /**产品系列ID*/
    public static final String MODEL_ID = "model_id";
    /**技术参数名称*/
    public static final String PARAM_NAME = "param_name";
    /**技术参数数值，保留范围条件和文字*/
    public static final String PARAM_VALUE = "param_value";
    /**单位*/
    public static final String UNIT = "unit";
    /**展示顺序*/
    public static final String SORT_RANK = "sort_rank";
    /**备注*/
    public static final String REMARK = "remark";
	/**
	 * 雪花ID
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 雪花ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Long", remark="雪花ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 产品系列ID
	 */
	public M setModelId(java.lang.Long modelId) {
		set("model_id", modelId);
		return (M)this;
	}
	
	/**
	 * 产品系列ID
	 */
	@JBoltField(name="modelId" ,columnName="model_id",type="Long", remark="产品系列ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getModelId() {
		return getLong("model_id");
	}

	/**
	 * 技术参数名称
	 */
	public M setParamName(java.lang.String paramName) {
		set("param_name", paramName);
		return (M)this;
	}
	
	/**
	 * 技术参数名称
	 */
	@JBoltField(name="paramName" ,columnName="param_name",type="String", remark="技术参数名称", required=true, maxLength=200, fixed=0, order=3)
	public java.lang.String getParamName() {
		return getStr("param_name");
	}

	/**
	 * 技术参数数值，保留范围条件和文字
	 */
	public M setParamValue(java.lang.String paramValue) {
		set("param_value", paramValue);
		return (M)this;
	}
	
	/**
	 * 技术参数数值，保留范围条件和文字
	 */
	@JBoltField(name="paramValue" ,columnName="param_value",type="String", remark="技术参数数值，保留范围条件和文字", required=true, maxLength=65535, fixed=0, order=4)
	public java.lang.String getParamValue() {
		return getStr("param_value");
	}

	/**
	 * 单位
	 */
	public M setUnit(java.lang.String unit) {
		set("unit", unit);
		return (M)this;
	}
	
	/**
	 * 单位
	 */
	@JBoltField(name="unit" ,columnName="unit",type="String", remark="单位", required=false, maxLength=100, fixed=0, order=5)
	public java.lang.String getUnit() {
		return getStr("unit");
	}

	/**
	 * 展示顺序
	 */
	public M setSortRank(java.lang.Integer sortRank) {
		set("sort_rank", sortRank);
		return (M)this;
	}
	
	/**
	 * 展示顺序
	 */
	@JBoltField(name="sortRank" ,columnName="sort_rank",type="Integer", remark="展示顺序", required=true, maxLength=10, fixed=0, order=6)
	public java.lang.Integer getSortRank() {
		return getInt("sort_rank");
	}

	/**
	 * 备注
	 */
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	/**
	 * 备注
	 */
	@JBoltField(name="remark" ,columnName="remark",type="String", remark="备注", required=false, maxLength=500, fixed=0, order=7)
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}

