package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔质管部：API调用日志表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseApiCallLog<M extends BaseApiCallLog<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /**主键ID(雪花算法)*/
    public static final String ID = "id";
    /**API路径(如:/api/siargo/order/status)*/
    public static final String API_PATH = "api_path";
    /**请求方法(GET/POST)*/
    public static final String API_METHOD = "api_method";
    /**订单号(单个查询)*/
    public static final String ORDER_ID = "order_id";
    /**订单号列表(批量查询,逗号分隔)*/
    public static final String ORDER_IDS = "order_ids";
    /**请求IP地址*/
    public static final String REQUEST_IP = "request_ip";
    /**客户端User-Agent*/
    public static final String USER_AGENT = "user_agent";
    /**响应状态(ok/fail)*/
    public static final String RESPONSE_STATUS = "response_status";
    /**响应业务状态码(200/1001/1002等)*/
    public static final String RESPONSE_CODE = "response_code";
    /**响应消息*/
    public static final String RESPONSE_MSG = "response_msg";
    /**请求耗时(毫秒)*/
    public static final String COST_TIME = "cost_time";
    /**JBolt应用ID*/
    public static final String JBOLT_APP_ID = "jbolt_app_id";
    /**调用时间*/
    public static final String CREATE_TIME = "create_time";
	/**
	 * 主键ID(雪花算法)
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID(雪花算法)
	 */
	@JBoltField(name="id" ,columnName="id",type="Long", remark="主键ID(雪花算法)", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * API路径(如:/api/siargo/order/status)
	 */
	public M setApiPath(java.lang.String apiPath) {
		set("api_path", apiPath);
		return (M)this;
	}
	
	/**
	 * API路径(如:/api/siargo/order/status)
	 */
	@JBoltField(name="apiPath" ,columnName="api_path",type="String", remark="API路径(如:/api/siargo/order/status)", required=true, maxLength=255, fixed=0, order=2)
	public java.lang.String getApiPath() {
		return getStr("api_path");
	}

	/**
	 * 请求方法(GET/POST)
	 */
	public M setApiMethod(java.lang.String apiMethod) {
		set("api_method", apiMethod);
		return (M)this;
	}
	
	/**
	 * 请求方法(GET/POST)
	 */
	@JBoltField(name="apiMethod" ,columnName="api_method",type="String", remark="请求方法(GET/POST)", required=true, maxLength=10, fixed=0, order=3)
	public java.lang.String getApiMethod() {
		return getStr("api_method");
	}

	/**
	 * 订单号(单个查询)
	 */
	public M setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	/**
	 * 订单号(单个查询)
	 */
	@JBoltField(name="orderId" ,columnName="order_id",type="String", remark="订单号(单个查询)", required=false, maxLength=100, fixed=0, order=4)
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	/**
	 * 订单号列表(批量查询,逗号分隔)
	 */
	public M setOrderIds(java.lang.String orderIds) {
		set("order_ids", orderIds);
		return (M)this;
	}
	
	/**
	 * 订单号列表(批量查询,逗号分隔)
	 */
	@JBoltField(name="orderIds" ,columnName="order_ids",type="String", remark="订单号列表(批量查询,逗号分隔)", required=false, maxLength=1000, fixed=0, order=5)
	public java.lang.String getOrderIds() {
		return getStr("order_ids");
	}

	/**
	 * 请求IP地址
	 */
	public M setRequestIp(java.lang.String requestIp) {
		set("request_ip", requestIp);
		return (M)this;
	}
	
	/**
	 * 请求IP地址
	 */
	@JBoltField(name="requestIp" ,columnName="request_ip",type="String", remark="请求IP地址", required=false, maxLength=50, fixed=0, order=6)
	public java.lang.String getRequestIp() {
		return getStr("request_ip");
	}

	/**
	 * 客户端User-Agent
	 */
	public M setUserAgent(java.lang.String userAgent) {
		set("user_agent", userAgent);
		return (M)this;
	}
	
	/**
	 * 客户端User-Agent
	 */
	@JBoltField(name="userAgent" ,columnName="user_agent",type="String", remark="客户端User-Agent", required=false, maxLength=500, fixed=0, order=7)
	public java.lang.String getUserAgent() {
		return getStr("user_agent");
	}

	/**
	 * 响应状态(ok/fail)
	 */
	public M setResponseStatus(java.lang.String responseStatus) {
		set("response_status", responseStatus);
		return (M)this;
	}
	
	/**
	 * 响应状态(ok/fail)
	 */
	@JBoltField(name="responseStatus" ,columnName="response_status",type="String", remark="响应状态(ok/fail)", required=true, maxLength=20, fixed=0, order=8)
	public java.lang.String getResponseStatus() {
		return getStr("response_status");
	}

	/**
	 * 响应业务状态码(200/1001/1002等)
	 */
	public M setResponseCode(java.lang.Integer responseCode) {
		set("response_code", responseCode);
		return (M)this;
	}
	
	/**
	 * 响应业务状态码(200/1001/1002等)
	 */
	@JBoltField(name="responseCode" ,columnName="response_code",type="Integer", remark="响应业务状态码(200/1001/1002等)", required=false, maxLength=10, fixed=0, order=9)
	public java.lang.Integer getResponseCode() {
		return getInt("response_code");
	}

	/**
	 * 响应消息
	 */
	public M setResponseMsg(java.lang.String responseMsg) {
		set("response_msg", responseMsg);
		return (M)this;
	}
	
	/**
	 * 响应消息
	 */
	@JBoltField(name="responseMsg" ,columnName="response_msg",type="String", remark="响应消息", required=false, maxLength=255, fixed=0, order=10)
	public java.lang.String getResponseMsg() {
		return getStr("response_msg");
	}

	/**
	 * 请求耗时(毫秒)
	 */
	public M setCostTime(java.lang.Long costTime) {
		set("cost_time", costTime);
		return (M)this;
	}
	
	/**
	 * 请求耗时(毫秒)
	 */
	@JBoltField(name="costTime" ,columnName="cost_time",type="Long", remark="请求耗时(毫秒)", required=false, maxLength=19, fixed=0, order=11)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getCostTime() {
		return getLong("cost_time");
	}

	/**
	 * JBolt应用ID
	 */
	public M setJboltAppId(java.lang.Long jboltAppId) {
		set("jbolt_app_id", jboltAppId);
		return (M)this;
	}
	
	/**
	 * JBolt应用ID
	 */
	@JBoltField(name="jboltAppId" ,columnName="jbolt_app_id",type="Long", remark="JBolt应用ID", required=false, maxLength=19, fixed=0, order=12)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getJboltAppId() {
		return getLong("jbolt_app_id");
	}

	/**
	 * 调用时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 调用时间
	 */
	@JBoltField(name="createTime" ,columnName="create_time",type="Date", remark="调用时间", required=true, maxLength=19, fixed=0, order=13)
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

}

