package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔质管部：产品参数种类值表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProdParamValue<M extends BaseProdParamValue<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /**主键(雪花ID)*/
    public static final String ID = "id";
    /**所属参数种类id(siargo_prod_param_type.id，多对一)*/
    public static final String PARAM_TYPE_ID = "param_type_id";
    /***/
    public static final String PARAM_VALUE = "param_value";
    /**描述*/
    public static final String DESCRIPTION = "description";
    /**同一种类内展示排序*/
    public static final String SORT_RANK = "sort_rank";
    /**1启用/0停用*/
    public static final String IS_ACTIVE = "is_active";
	/**
	 * 主键(雪花ID)
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键(雪花ID)
	 */
	@JBoltField(name="id" ,columnName="id",type="Long", remark="主键(雪花ID)", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 所属参数种类id(siargo_prod_param_type.id，多对一)
	 */
	public M setParamTypeId(java.lang.Long paramTypeId) {
		set("param_type_id", paramTypeId);
		return (M)this;
	}
	
	/**
	 * 所属参数种类id(siargo_prod_param_type.id，多对一)
	 */
	@JBoltField(name="paramTypeId" ,columnName="param_type_id",type="Long", remark="参数种类", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getParamTypeId() {
		return getLong("param_type_id");
	}

	public M setParamValue(java.lang.String paramValue) {
		set("param_value", paramValue);
		return (M)this;
	}
	
	@JBoltField(name="paramValue" ,columnName="param_value",type="String", remark="参数值", required=false, maxLength=50, fixed=0, order=3)
	public java.lang.String getParamValue() {
		return getStr("param_value");
	}

	/**
	 * 描述
	 */
	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	/**
	 * 描述
	 */
	@JBoltField(name="description" ,columnName="description",type="String", remark="描述", required=false, maxLength=200, fixed=0, order=4)
	public java.lang.String getDescription() {
		return getStr("description");
	}

	/**
	 * 同一种类内展示排序
	 */
	public M setSortRank(java.lang.Integer sortRank) {
		set("sort_rank", sortRank);
		return (M)this;
	}
	
	/**
	 * 同一种类内展示排序
	 */
	@JBoltField(name="sortRank" ,columnName="sort_rank",type="Integer", remark="同一种类内展示排序", required=true, maxLength=10, fixed=0, order=5)
	public java.lang.Integer getSortRank() {
		return getInt("sort_rank");
	}

	/**
	 * 1启用/0停用
	 */
	public M setIsActive(java.lang.Integer isActive) {
		set("is_active", isActive);
		return (M)this;
	}
	
	/**
	 * 1启用/0停用
	 */
	@JBoltField(name="isActive" ,columnName="is_active",type="Integer", remark="1启用/0停用", required=true, maxLength=3, fixed=0, order=6)
	public java.lang.Integer getIsActive() {
		return getInt("is_active");
	}

}

