package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔文件关键字表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDmsFileKeyword<M extends BaseDmsFileKeyword<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /**主键ID*/
    public static final String ID = "id";
    /**文件ID*/
    public static final String FILE_ID = "file_id";
    /**关键字*/
    public static final String KEYWORD = "keyword";
	/**
	 * 主键ID
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Long", remark="主键ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 文件ID
	 */
	public M setFileId(java.lang.Long fileId) {
		set("file_id", fileId);
		return (M)this;
	}
	
	/**
	 * 文件ID
	 */
	@JBoltField(name="fileId" ,columnName="file_id",type="Long", remark="文件ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getFileId() {
		return getLong("file_id");
	}

	/**
	 * 关键字
	 */
	public M setKeyword(java.lang.String keyword) {
		set("keyword", keyword);
		return (M)this;
	}
	
	/**
	 * 关键字
	 */
	@JBoltField(name="keyword" ,columnName="keyword",type="String", remark="关键字", required=false, maxLength=200, fixed=0, order=3)
	public java.lang.String getKeyword() {
		return getStr("keyword");
	}

}

