package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 矽翔质管部：检校批次表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEquipmentInspectionBatch<M extends BaseEquipmentInspectionBatch<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /***/
    public static final String ID = "id";
    /**设备ID*/
    public static final String EQUIPMENT_ID = "equipment_id";
    /**检校日期*/
    public static final String BATCH_DATE = "batch_date";
    /**检校概况描述*/
    public static final String DESCRIPTION = "description";
    /**设备检定状态：1-合格 2-不合格*/
    public static final String STATUS = "status";
    /**编制人，关联jb_user.id*/
    public static final String CREATOR_ID = "creator_id";
    /**审核人，关联jb_user.id*/
    public static final String AUDITOR_ID = "auditor_id";
    /**编制时间*/
    public static final String CREATOR_TIME = "creator_time";
    /**审核时间*/
    public static final String AUDITOR_TIME = "auditor_time";
    /**审核状态 0-未审核 1-待审核 2-已审核*/
    public static final String AUDIT_STATUS = "audit_status";
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	@JBoltField(name="id" ,columnName="id",type="Long", remark="ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 设备ID
	 */
	public M setEquipmentId(java.lang.Long equipmentId) {
		set("equipment_id", equipmentId);
		return (M)this;
	}
	
	/**
	 * 设备ID
	 */
	@JBoltField(name="equipmentId" ,columnName="equipment_id",type="Long", remark="设备ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getEquipmentId() {
		return getLong("equipment_id");
	}

	/**
	 * 检校日期
	 */
	public M setBatchDate(java.util.Date batchDate) {
		set("batch_date", batchDate);
		return (M)this;
	}
	
	/**
	 * 检校日期
	 */
	@JBoltField(name="batchDate" ,columnName="batch_date",type="Date", remark="检校日期", required=true, maxLength=10, fixed=0, order=3)
	public java.util.Date getBatchDate() {
		return getDate("batch_date");
	}

	/**
	 * 检校概况描述
	 */
	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	/**
	 * 检校概况描述
	 */
	@JBoltField(name="description" ,columnName="description",type="String", remark="检校概况描述", required=false, maxLength=500, fixed=0, order=4)
	public java.lang.String getDescription() {
		return getStr("description");
	}

	/**
	 * 设备检定状态：1-合格 2-不合格
	 */
	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	/**
	 * 设备检定状态：1-合格 2-不合格
	 */
	@JBoltField(name="status" ,columnName="status",type="Integer", remark="设备检定状态：1-合格 2-不合格", required=true, maxLength=3, fixed=0, order=5)
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 编制人，关联jb_user.id
	 */
	public M setCreatorId(java.lang.Long creatorId) {
		set("creator_id", creatorId);
		return (M)this;
	}
	
	/**
	 * 编制人，关联jb_user.id
	 */
	@JBoltField(name="creatorId" ,columnName="creator_id",type="Long", remark="编制人，关联jb_user.id", required=false, maxLength=19, fixed=0, order=6)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getCreatorId() {
		return getLong("creator_id");
	}

	/**
	 * 审核人，关联jb_user.id
	 */
	public M setAuditorId(java.lang.Long auditorId) {
		set("auditor_id", auditorId);
		return (M)this;
	}
	
	/**
	 * 审核人，关联jb_user.id
	 */
	@JBoltField(name="auditorId" ,columnName="auditor_id",type="Long", remark="审核人，关联jb_user.id", required=false, maxLength=19, fixed=0, order=7)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getAuditorId() {
		return getLong("auditor_id");
	}

	/**
	 * 编制时间
	 */
	public M setCreatorTime(java.util.Date creatorTime) {
		set("creator_time", creatorTime);
		return (M)this;
	}
	
	/**
	 * 编制时间
	 */
	@JBoltField(name="creatorTime" ,columnName="creator_time",type="Date", remark="编制时间", required=false, maxLength=19, fixed=0, order=8)
	public java.util.Date getCreatorTime() {
		return getDate("creator_time");
	}

	/**
	 * 审核时间
	 */
	public M setAuditorTime(java.util.Date auditorTime) {
		set("auditor_time", auditorTime);
		return (M)this;
	}
	
	/**
	 * 审核时间
	 */
	@JBoltField(name="auditorTime" ,columnName="auditor_time",type="Date", remark="审核时间", required=false, maxLength=19, fixed=0, order=9)
	public java.util.Date getAuditorTime() {
		return getDate("auditor_time");
	}

	/**
	 * 审核状态 0-未审核 1-待审核 2-已审核
	 */
	public M setAuditStatus(java.lang.Integer auditStatus) {
		set("audit_status", auditStatus);
		return (M)this;
	}
	
	/**
	 * 审核状态 0-未审核 1-待审核 2-已审核
	 */
	@JBoltField(name="auditStatus" ,columnName="audit_status",type="Integer", remark="审核状态 0-未审核 1-待审核 2-已审核", required=true, maxLength=3, fixed=0, order=10)
	public java.lang.Integer getAuditStatus() {
		return getInt("audit_status");
	}

}

