package cn.jbolt.siargo.model.base;
import cn.jbolt.core.model.base.JBoltBaseModel;
import cn.jbolt.core.gen.JBoltField;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.ToStringSerializer;

/**
 * 订单里的产品型号，跟报告单多对一关系
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProduct<M extends BaseProduct<M>> extends JBoltBaseModel<M>{
    public static final String DATASOURCE_CONFIG_NAME = "main";
    /**产品ID*/
    public static final String ID = "id";
    /**检验报告单ID*/
    public static final String REPORT_ID = "report_id";
    /**产品类型: 1传感器,  2小流量, 3大流量*/
    public static final String TYPE = "type";
    /**产品型号*/
    public static final String MODLE = "modle";
    /**送检数量 (Quantity Submitted for Inspection)*/
    public static final String QSI = "qsi";
    /**检验数量 (Quantity Inspected)*/
    public static final String QI = "qi";
    /**产品编号*/
    public static final String NUMBER = "number";
    /**流量范围(Flow Range)*/
    public static final String FLOW_RANGE = "flow_range";
    /**备注*/
    public static final String DES = "des";
    /**删除时间*/
    public static final String DELETE_TIME = "delete_time";
    /**有效数据(valid data)*/
    public static final String VD = "vd";
    /**检验进度(Inspection Progress)： 1未开始检验, 2精度合格, 3功能合格, 4外观合格, 5全部合格*/
    public static final String INSP = "insp";
    /**精度检验日期(Accuracy qualified)*/
    public static final String ACCQ_TIME = "accq_time";
    /**功能检验日期(Function qualified)*/
    public static final String FUNQ_TIME = "funq_time";
    /**外观检验日期(Appearance qualified)*/
    public static final String APPQ_TIME = "appq_time";
    /**最终审核日期(All qualified)*/
    public static final String ALLQ_TIME = "allq_time";
    /**精度合格检验人*/
    public static final String ACCQ_UID = "accq_uid";
    /**功能合格检验人*/
    public static final String FUNQ_UID = "funq_uid";
    /**外观合格检验人*/
    public static final String APPQ_UID = "appq_uid";
    /**最终审核人*/
    public static final String ALLQ_UID = "allq_uid";
    /**pdf地址*/
    public static final String PDFSTR = "pdfstr";
    /**pdf报告单版本号*/
    public static final String PDFVER = "pdfver";
    /**整机电流 (Complete Unit Current)*/
    public static final String CUC = "cuc";
    /**整机电流24v*/
    public static final String CUCMAX = "cucmax";
    /**整机电流8v/12*/
    public static final String CUCMIN = "cucmin";
    /**脉冲电压(Pulse Voltage)*/
    public static final String PV = "pv";
    /**热头电压(Thermal Head Voltage)*/
    public static final String THV = "thv";
    /**零点内码(Zero Point)*/
    public static final String ZP = "zp";
    /**故障电平(Fault Level)*/
    public static final String FL = "fl";
    /**电池电压(Battery Voltage)*/
    public static final String BV = "bv";
    /**本地地址(Local Address)*/
    public static final String LA = "la";
    
    
	/**
	 * 产品ID
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 产品ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Long", remark="产品ID", required=true, maxLength=19, fixed=0, order=1)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 检验报告单ID
	 */
	public M setReportId(java.lang.Long reportId) {
		set("report_id", reportId);
		return (M)this;
	}
	
	/**
	 * 检验报告单ID
	 */
	@JBoltField(name="reportId" ,columnName="report_id",type="Long", remark="检验报告单ID", required=true, maxLength=19, fixed=0, order=2)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getReportId() {
		return getLong("report_id");
	}

	/**产品类型: 1传感器,  2小流量, 3大流量*/
	public M setType(java.lang.Long type) {
		set("type", type);
		return (M)this;
	}
	
	/**产品类型: 1传感器,  2小流量, 3大流量*/
	@JBoltField(name="type" ,columnName="type",type="Long", remark="产品类型:0小流量, 1传感器, 2大流量", required=true, maxLength=10, fixed=0, order=3)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getType() {
		return getLong("type");
	}

	/**
	 * 产品型号
	 */
	public M setModle(java.lang.String modle) {
		set("modle", modle);
		return (M)this;
	}
	
	/**
	 * 产品型号
	 */
	@JBoltField(name="modle" ,columnName="modle",type="String", remark="产品型号", required=false, maxLength=255, fixed=0, order=4)
	public java.lang.String getModle() {
		return getStr("modle");
	}

	/**
	 * 送检数量 (Quantity Submitted for Inspection)
	 */
	public M setQsi(java.lang.Long qsi) {
		set("qsi", qsi);
		return (M)this;
	}
	
	/**
	 * 送检数量 (Quantity Submitted for Inspection)
	 */
	@JBoltField(name="qsi" ,columnName="qsi",type="Long", remark="送检数量 (Quantity Submitted for Inspection)", required=true, maxLength=10, fixed=0, order=5)
	public java.lang.Long getQsi() {
		return getLong("qsi");
	}

	/**
	 * 检验数量 (Quantity Inspected)
	 */
	public M setQi(java.lang.Long qi) {
		set("qi", qi);
		return (M)this;
	}
	
	/**
	 * 检验数量 (Quantity Inspected)
	 */
	@JBoltField(name="qi" ,columnName="qi",type="Long", remark="检验数量 (Quantity Inspected)", required=true, maxLength=10, fixed=0, order=6)
	@JSONField(serializeUsing= ToStringSerializer.class)
	public java.lang.Long getQi() {
		return getLong("qi");
	}

	/**
	 * 产品编号
	 */
	public M setNumber(java.lang.String number) {
		set("number", number);
		return (M)this;
	}
	
	/**
	 * 产品编号
	 */
	@JBoltField(name="number" ,columnName="number",type="String", remark="产品编号", required=false, maxLength=255, fixed=0, order=7)
	public java.lang.String getNumber() {
		return getStr("number");
	}

	/**
	 * 流量范围(Flow Range)
	 */
	public M setFlowRange(java.lang.String flowRange) {
		set("flow_range", flowRange);
		return (M)this;
	}
	
	/**
	 * 流量范围(Flow Range)
	 */
	@JBoltField(name="flowRange" ,columnName="flow_range",type="String", remark="流量范围(Flow Range)", required=false, maxLength=255, fixed=0, order=8)
	public java.lang.String getFlowRange() {
		return getStr("flow_range");
	}

	/**
	 * 备注
	 */
	public M setDes(java.lang.String des) {
		set("des", des);
		return (M)this;
	}
	
	/**
	 * 备注
	 */
	@JBoltField(name="des" ,columnName="des",type="String", remark="备注", required=false, maxLength=255, fixed=0, order=9)
	public java.lang.String getDes() {
		return getStr("des");
	}

	/**
	 * 删除时间
	 */
	public M setDeleteTime(java.util.Date deleteTime) {
		set("delete_time", deleteTime);
		return (M)this;
	}
	
	/**
	 * 删除时间
	 */
	@JBoltField(name="deleteTime" ,columnName="delete_time",type="Date", remark="删除时间", required=false, maxLength=19, fixed=0, order=10)
	public java.util.Date getDeleteTime() {
		return getDate("delete_time");
	}

	/**
	 * 有效数据(valid data)
	 */
	public M setVd(java.lang.Integer vd) {
		set("vd", vd);
		return (M)this;
	}
	
	/**
	 * 有效数据(valid data)
	 */
	@JBoltField(name="vd" ,columnName="vd",type="Integer", remark="有效数据(valid data)", required=true, maxLength=10, fixed=0, order=11)
	public java.lang.Integer getVd() {
		return getInt("vd");
	}

	/**
	 * 检验进度(Inspection Progress)： 1未开始检验,  2精度合格,  3功能合格,  4外观合格, 5全部合格
	 */
	public M setInsp(java.lang.Integer insp) {
		set("insp", insp);
		return (M)this;
	}
	
	/**
	 * 检验进度(Inspection Progress)：1未开始检验, 2精度合格, 3功能合格, 4外观合格, 5全部合格
	 */
	@JBoltField(name="insp" ,columnName="insp",type="Integer", remark="检验进度(Inspection Progress)：1未开始检验, 2精度合格, 3功能合格, 4外观合格, 5全部合格", required=true, maxLength=3, fixed=0, order=12)
	public java.lang.Integer getInsp() {
		return getInt("insp");
	}

	/**
	 * 精度检验日期(Accuracy qualified)
	 */
	public M setAccqTime(java.util.Date accqTime) {
		set("accq_time", accqTime);
		return (M)this;
	}
	
	/**
	 * 精度检验日期(Accuracy qualified)
	 */
	@JBoltField(name="accqTime" ,columnName="accq_time",type="Date", remark="精度检验日期(Accuracy qualified)", required=false, maxLength=19, fixed=0, order=13)
	public java.util.Date getAccqTime() {
		return getDate("accq_time");
	}

	/**
	 * 功能检验日期(Function qualified)
	 */
	public M setFunqTime(java.util.Date funqTime) {
		set("funq_time", funqTime);
		return (M)this;
	}
	
	/**
	 * 功能检验日期(Function qualified)
	 */
	@JBoltField(name="funqTime" ,columnName="funq_time",type="Date", remark="功能检验日期(Function qualified)", required=false, maxLength=19, fixed=0, order=14)
	public java.util.Date getFunqTime() {
		return getDate("funq_time");
	}

	/**
	 * 外观检验日期(Appearance qualified)
	 */
	public M setAppqTime(java.util.Date appqTime) {
		set("appq_time", appqTime);
		return (M)this;
	}
	
	/**
	 * 外观检验日期(Appearance qualified)
	 */
	@JBoltField(name="appqTime" ,columnName="appq_time",type="Date", remark="外观检验日期(Appearance qualified)", required=false, maxLength=19, fixed=0, order=15)
	public java.util.Date getAppqTime() {
		return getDate("appq_time");
	}

	/**
	 * 最终审核日期(All qualified)
	 */
	public M setAllqTime(java.util.Date allqTime) {
		set("allq_time", allqTime);
		return (M)this;
	}
	
	/**
	 * 最终审核日期(All qualified)
	 */
	@JBoltField(name="allqTime" ,columnName="allq_time",type="Date", remark="最终审核日期(All qualified)", required=false, maxLength=19, fixed=0, order=16)
	public java.util.Date getAllqTime() {
		return getDate("allq_time");
	}

	/**
	 * 精度合格检验人
	 */
	public M setAccqUid(java.math.BigInteger accqUid) {
		set("accq_uid", accqUid);
		return (M)this;
	}
	
	/**
	 * 精度合格检验人
	 */
	@JBoltField(name="accqUid" ,columnName="accq_uid",type="", remark="精度合格检验人", required=false, maxLength=20, fixed=0, order=17)
	public java.math.BigInteger getAccqUid() {
		return getBigInteger("accq_uid");
	}

	/**
	 * 功能合格检验人
	 */
	public M setFunqUid(java.math.BigInteger funqUid) {
		set("funq_uid", funqUid);
		return (M)this;
	}
	
	/**
	 * 功能合格检验人
	 */
	@JBoltField(name="funqUid" ,columnName="funq_uid",type="", remark="功能合格检验人", required=false, maxLength=20, fixed=0, order=18)
	public java.math.BigInteger getFunqUid() {
		return getBigInteger("funq_uid");
	}

	/**
	 * 外观合格检验人
	 */
	public M setAppqUid(java.math.BigInteger appqUid) {
		set("appq_uid", appqUid);
		return (M)this;
	}
	
	/**
	 * 外观合格检验人
	 */
	@JBoltField(name="appqUid" ,columnName="appq_uid",type="", remark="外观合格检验人", required=false, maxLength=20, fixed=0, order=19)
	public java.math.BigInteger getAppqUid() {
		return getBigInteger("appq_uid");
	}

	/**
	 * 最终审核人
	 */
	public M setAllqUid(java.math.BigInteger allqUid) {
		set("allq_uid", allqUid);
		return (M)this;
	}
	
	/**
	 * 最终审核人
	 */
	@JBoltField(name="allqUid" ,columnName="allq_uid",type="", remark="最终审核人", required=false, maxLength=20, fixed=0, order=20)
	public java.math.BigInteger getAllqUid() {
		return getBigInteger("allq_uid");
	}

	/**
	 * pdf地址
	 */
	public M setPdfstr(java.lang.String pdfstr) {
		set("pdfstr", pdfstr);
		return (M)this;
	}
	
	/**
	 * pdf地址
	 */
	@JBoltField(name="pdfstr" ,columnName="pdfstr",type="String", remark="pdf地址", required=false, maxLength=255, fixed=0, order=21)
	public java.lang.String getPdfstr() {
		return getStr("pdfstr");
	}
	
	/**
	 * pdf报告单版本号
	 */
	public M setPdfver(java.lang.String pdfver) {
		set("pdfstr", pdfver);
		return (M)this;
	}
	
	/**
	 * pdf报告单版本号
	 */
	@JBoltField(name="pdfver" ,columnName="pdfver",type="String", remark="pdf报告单版本号", required=false, maxLength=255, fixed=0, order=22)
	public java.lang.String getPdfver() {
		return getStr("pdfver");
	}

	/**
	 * 整机电流 (Complete Unit Current)
	 */
	public M setCuc(java.lang.Double cuc) {
		set("cuc", cuc);
		return (M)this;
	}
	
	/**
	 * 整机电流 (Complete Unit Current)
	 */
	@JBoltField(name="cuc" ,columnName="cuc",type="Double", remark="整机电流 (Complete Unit Current)", required=false, maxLength=4, fixed=2, order=23)
	public java.lang.Double getCuc() {
		return getDouble("cuc");
	}

	/**
	 * 整机电流24v
	 */
	public M setCucmax(java.lang.Double cucmax) {
		set("cucmax", cucmax);
		return (M)this;
	}
	
	/**
	 * 整机电流24v
	 */
	@JBoltField(name="cucmax" ,columnName="cucmax",type="Double", remark="整机电流24v", required=false, maxLength=4, fixed=2, order=24)
	public java.lang.Double getCucmax() {
		return getDouble("cucmax");
	}

	/**
	 * 整机电流8v
	 */
	public M setCucmin(java.lang.Double cucmin) {
		set("cucmin", cucmin);
		return (M)this;
	}
	
	/**
	 * 整机电流8v
	 */
	@JBoltField(name="cucmin" ,columnName="cucmin",type="Double", remark="整机电流8/12v", required=false, maxLength=4, fixed=2, order=25)
	public java.lang.Double getCucmin() {
		return getDouble("cucmin");
	}

	/**
	 * 脉冲电压(Pulse Voltage)
	 */
	public M setPv(java.lang.Double pv) {
		set("pv", pv);
		return (M)this;
	}
	
	/**
	 * 脉冲电压(Pulse Voltage)
	 */
	@JBoltField(name="pv" ,columnName="pv",type="Double", remark="脉冲电压(Pulse Voltage)", required=false, maxLength=4, fixed=2, order=26)
	public java.lang.Double getPv() {
		return getDouble("pv");
	}

	/**
	 * 热头电压(Thermal Head Voltage)
	 */
	public M setThv(java.lang.Integer thv) {
		set("thv", thv);
		return (M)this;
	}
	
	/**
	 * 热头电压(Thermal Head Voltage)
	 */
	@JBoltField(name="thv" ,columnName="thv",type="Integer", remark="热头电压(Thermal Head Voltage)", required=false, maxLength=4, fixed=0, order=27)
	public java.lang.Integer getThv() {
		return getInt("thv");
	}

	/**
	 * 零点内码(Zero Point)
	 */
	public M setZp(java.lang.Integer zp) {
		set("zp", zp);
		return (M)this;
	}
	
	/**
	 * 零点内码(Zero Point)
	 */
	@JBoltField(name="zp" ,columnName="zp",type="Integer", remark="零点内码(Zero Point)", required=false, maxLength=2, fixed=0, order=28)
	public java.lang.Integer getZp() {
		return getInt("zp");
	}

	/**
	 * 故障电平(Fault Level)
	 */
	public M setFl(java.lang.Double fl) {
		set("fl", fl);
		return (M)this;
	}
	
	/**
	 * 故障电平(Fault Level)
	 */
	@JBoltField(name="fl" ,columnName="fl",type="Double", remark="故障电平(Fault Level)", required=false, maxLength=4, fixed=2, order=29)
	public java.lang.Double getFl() {
		return getDouble("fl");
	}
	
	/**
	 * 电池电压(Battery Voltage)
	 */
	public M setBv(java.lang.Double bv) {
		set("bv", bv);
		return (M)this;
	}
	
	/**
	 * 电池电压(Battery Voltage)
	 */
	@JBoltField(name="bv" ,columnName="bv",type="Double", remark="电池电压(Battery Voltage)", required=false, maxLength=5, fixed=4, order=30)
	public java.lang.Double getBv() {
		return getDouble("bv");
	}
	
	/**
	 * 本地地址(Local Address)
	 */
	public M setLa(java.lang.Integer la) {
		set("la", la);
		return (M)this;
	}
	
	/**
	 * 本地地址(Local Address)
	 */
	@JBoltField(name="la" ,columnName="la",type="Integer", remark="本地地址(Local Address)", required=false, maxLength=2, fixed=0, order=31)
	public java.lang.Integer getLa() {
		return getInt("zp");
	}

}

